//! FFI Zone Classification and Language Detection
//!
//! Extracted from ffi_boundary.zig for better code organization.
//! Contains zone classification logic, language detection,
//! and boundary kind classification.

const std = @import("std");
const log = std.log.scoped(.ffi_zone);
const c = @import("../../../ir/llvm_raw.zig").c;

const Language = @import("../../../diag/issue.zig").FFIBoundary.Language;
const BoundaryKind = @import("../../../diag/issue.zig").FFIBoundary.BoundaryKind;
const PlatformProfile = @import("../../../semantics/platform_profile.zig").PlatformProfile;
const FunctionSemantics = @import("../../../registry/semantic_registry.zig").FunctionSemantics;
const SemanticRegistry = @import("../../../registry/semantic_registry.zig").SemanticRegistry;
const PatternRegistry = @import("../../../filter/pattern_registry.zig").PatternRegistry;
const PR_CSafetyLevel = @import("../../../filter/pattern_registry.zig").CSafetyLevel;

/// Re-export language classifier for unified access.
const lang_classifier = @import("ffi_language_classifier.zig");

/// Known FFI patterns for language identification.
pub const FFIPatterns = struct {
    /// Rust FFI function name patterns.
    pub const rust_patterns = &[_][]const u8{
        "extern",
        "rust_",
        "_ZN",
    };

    /// Zig FFI function name patterns (based on zig_ffi_filter.md).
    pub const zig_patterns = &[_][]const u8{
        "extern",
        "c_",
        "@cImport",
        "zig_",
        "__zig",
    };

    /// Go cgo FFI function name patterns.
    /// Covers: import"C" wrappers (C.xxx), cgo glue code, and runtime bridges.
    pub const go_patterns = &[_][]const u8{
        "C.", // import "C" → C.xxx function calls
        "_cgo_", // cgo glue functions (_cgo_expact, _cgo_allocate)
        "_Cfunc_", // C function wrapper generated by cgo
        "crosscall2", // Go runtime cross-call bridge
        "runtime.cgocall", // runtime.cgo call wrapper
    };

    /// Go-specific internal/runtime functions (SAFE — not real FFI issues).
    pub const go_internal_patterns = &[_][]const u8{
        "runtime.gopark",     "runtime.goexit",
        "runtime.morestack",  "runtime.mallocgc",
        "runtime.gcStart",    "runtime.gcStop",
        "runtime.makeslice",  "runtime.convT2E",
        "runtime.convE2T",    "runtime.assertE2T",
        "runtime.assertE2T2", "runtime.assertI2T",
        "runtime.assertI2T2", "runtime.panicwrap",
    };

    /// Zig-specific internal/runtime functions (SAFE — not real FFI issues).
    pub const zig_internal_patterns = &[_][]const u8{
        "zig_assert_fail",
        "zig_panic",
        "zig_oq",
        "zig_write",
        "zig_alloc",
        "zig_free",
        "zig_error",
        "zig_generic_resolve",
        "zig_monitor_init",
        "zig_monitor_lock",
        "zig_monitor_unlock",
        "zig_promote_error",
        "zig_demote_error",
        "zig_convert_to_error_union",
        "zig_stack_trace",
        "zig_debug_safe_truncate",
        "zig_debug_safety_crash",
        "__zig_bug",
        "__zig_panic_handler",
    };
};

// Local dangerous_c_functions array removed — consolidated into PatternRegistry.
// See: PatternRegistry.isDangerousCFunction

/// Check if a C function is in the dangerous blacklist.
///
/// Delegates to PatternRegistry.isDangerousCFunction (single source of truth).
pub fn isDangerousCFunction(name: []const u8) bool {
    return PatternRegistry.isDangerousCFunction(name);
}

/// Safety level classification for C functions imported via @cImport.
/// Re-export from PatternRegistry (single source of truth).
pub const CSafetyLevel = PR_CSafetyLevel;

// Local C safety classification arrays removed — consolidated into PatternRegistry.
// See: PatternRegistry.classifyCSafety, c_import_blacklist, c_import_conditional, c_import_safe

// Local zig_cimport_safe array removed — use classifyCSafetyLevel() instead.

/// Check if a Zig function is an internal/runtime function (SAFE — skip analysis).
///
/// Delegates to PatternRegistry.isLanguageInternal (single source of truth).
/// PatternRegistry.isLanguageInternal covers both Zig and Go internals;
/// a Zig function name will never match Go patterns in practice.
pub fn isZigInternalFunction(func_name: []const u8) bool {
    return PatternRegistry.isLanguageInternal(func_name);
}

/// Check if a Go function is an internal/runtime function (SAFE — skip analysis).
///
/// Delegates to PatternRegistry.isLanguageInternal (single source of truth).
pub fn isGoInternalFunction(func_name: []const u8) bool {
    return PatternRegistry.isLanguageInternal(func_name);
}

/// Check if a called C function from @cImport is a known-safe binding.
/// DEPRECATED: Use classifyCSafetyLevel() for three-tier filtering.
///
/// Returns true only for Layer 3 (presumed safe) functions.
pub fn isZigSafeCimport(func_name: []const u8) bool {
    const level = classifyCSafetyLevel(func_name);
    return level == .safe;
}

/// Classify the safety level of a C function imported via @cImport.
///
/// Delegates to PatternRegistry.classifyCSafety (single source of truth).
/// Returns null for unknown functions (conservative: not automatically safe).
pub fn classifyCSafetyLevel(func_name: []const u8) ?CSafetyLevel {
    return PatternRegistry.classifyCSafety(func_name);
}

/// Identify the language of a function based on its characteristics.
/// Delegates to unified language_detector (single source of truth).
pub fn identifyLanguage(func: c.LLVMValueRef) Language {
    return @import("../../../semantics/language_detector.zig").identifyLanguage(func);
}

/// Identify the language of a called function based on its name.
/// Delegates to unified language_detector (single source of truth).
pub fn identifyCalleeLanguage(func_name: []const u8) Language {
    return @import("../../../semantics/language_detector.zig").identifyCalleeLanguage(func_name);
}

/// Platform-aware callee language classification (Bug 2 fix).
/// Uses module-level language and PlatformProfile to disambiguate Zig vs Go.
pub fn identifyCalleeLanguageWithContext(
    func_name: []const u8,
    module_lang: Language,
    platform_profile: ?PlatformProfile,
) Language {
    return lang_classifier.identifyCalleeLanguageWithContext(func_name, module_lang, platform_profile);
}

/// Classify the boundary kind based on caller and callee languages.
pub fn classifyBoundaryKind(caller_lang: Language, callee_lang: Language) BoundaryKind {
    return lang_classifier.classifyBoundaryKind(caller_lang, callee_lang);
}

/// Check if a function name is a libc function.
pub fn isLibcFunction(func_name: []const u8) bool {
    return lang_classifier.isLibcFunction(func_name);
}

/// Classify FFI boundary with enhanced detection for dynamic loading/JNI/Python.
pub fn classifyBoundaryKindEnhanced(
    caller_lang: Language,
    callee_lang: Language,
    func_name: []const u8,
) BoundaryKind {
    return lang_classifier.classify_boundary_kind_enhanced(caller_lang, callee_lang, func_name);
}

/// Check if a function name represents a dynamic loading function.
pub fn isDynamicLoadingFunction(func_name: []const u8) bool {
    return lang_classifier.isDynamicLoadingFunction(func_name);
}

/// Check if a function name represents a JNI function.
pub fn isJNIFunction(func_name: []const u8) bool {
    return lang_classifier.isJNIFunction(func_name);
}

/// Check if a function name represents a Python C API function.
pub fn isPythonCApiFunction(func_name: []const u8) bool {
    return lang_classifier.isPythonCApiFunction(func_name);
}

/// Comprehensive check: Should we analyze this FFI boundary in Zig context?
/// Returns true if this is a REAL FFI risk worth reporting.
/// Uses three-tier safety classification for accurate filtering.
pub fn isZigFFIWorthReporting(
    caller_func_name: []const u8,
    callee_func_name: []const u8,
    sem: FunctionSemantics,
) bool {
    // Rule 1: Skip if caller is Zig internal function
    if (isZigInternalFunction(caller_func_name)) {
        return false;
    }

    // Rule 2: Use three-tier safety classification for callee
    const safety_level = classifyCSafetyLevel(callee_func_name);

    if (safety_level) |level| {
        switch (level) {
            // Layer 1: Always report dangerous functions
            .dangerous => {
                return true; // system(), strcpy(), gets() - always warn
            },

            // Layer 2: Conditional - report based on semantics and usage patterns
            .conditional => {
                // Report if semantically dangerous or has ownership issues
                if (sem.kind == .command_exec or
                    sem.kind == .unchecked_copy or
                    sem.transfers_ownership or
                    sem.consumes_ownership)
                {
                    return true;
                }
                // For conditional functions, still report format string issues
                if (sem.kind == .format_string) {
                    return true;
                }
                // Default: don't report for well-used conditional functions
                // (caller can add additional heuristics if needed)
                return false;
            },

            // Layer 3: Safe functions - skip unless special case
            .safe => {
                // Still report if it's semantically unusual (defensive)
                if (sem.kind == .command_exec or sem.kind == .unchecked_copy) {
                    return true; // Override: unexpected dangerous pattern
                }
                return false; // Safe libc bindings are OK
            },
        }
    } else {
        // Unknown function → conservative: analyze it
        // This ensures new/unknown C imports get proper scrutiny
    }

    // Rule 3: Always report cross-language ownership issues
    if (sem.transfers_ownership or sem.consumes_ownership) {
        return true;
    }

    // Rule 4: Report format string vulnerabilities
    if (sem.kind == .format_string) {
        return true;
    }

    // Default: report for analysis (conservative for unknown functions)
    return true;
}

/// Check if a function name represents a dangerous FFI pattern.
/// Uses Semantic Registry for comprehensive risk assessment.
pub fn isDangerousPattern(func_name: []const u8) bool {
    return SemanticRegistry.isKnown(func_name);
}

/// Check if a caller function name suggests intentional/safe/test code.
///
/// Delegates to PatternRegistry.isIntentionalPattern (single source of truth).
pub fn isLikelyIntentionalPattern(func_name: []const u8) bool {
    return PatternRegistry.isIntentionalPattern(func_name);
}

// ============================================================================
// Tests
// ============================================================================

test "DangerousCFunction: buffer overflow functions are detected" {
    try std.testing.expect(isDangerousCFunction("strcpy"));
    try std.testing.expect(isDangerousCFunction("strcat"));
    try std.testing.expect(isDangerousCFunction("sprintf"));
    try std.testing.expect(isDangerousCFunction("gets"));
    try std.testing.expect(isDangerousCFunction("scanf"));
    try std.testing.expect(isDangerousCFunction("vsprintf"));
}

test "DangerousCFunction: command injection functions are detected" {
    try std.testing.expect(isDangerousCFunction("system"));
    try std.testing.expect(isDangerousCFunction("popen"));
    try std.testing.expect(isDangerousCFunction("execl"));
    try std.testing.expect(isDangerousCFunction("execve"));
    try std.testing.expect(isDangerousCFunction("execvp"));
}

test "DangerousCFunction: deprecated/race condition functions" {
    try std.testing.expect(isDangerousCFunction("strtok"));
    try std.testing.expect(isDangerousCFunction("asctime"));
    try std.testing.expect(isDangerousCFunction("ctime"));
    try std.testing.expect(isDangerousCFunction("gmtime"));
    try std.testing.expect(isDangerousCFunction("localtime"));
    try std.testing.expect(isDangerousCFunction("bcopy"));
    try std.testing.expect(isDangerousCFunction("bzero"));
}

test "DangerousCFunction: format string vulnerability functions" {
    try std.testing.expect(isDangerousCFunction("fprintf"));
    try std.testing.expect(isDangerousCFunction("printf"));
    try std.testing.expect(isDangerousCFunction("sscanf"));
    try std.testing.expect(isDangerousCFunction("fscanf"));
}

test "DangerousCFunction: safe functions are NOT flagged" {
    try std.testing.expect(!isDangerousCFunction("memcpy"));
    try std.testing.expect(!isDangerousCFunction("snprintf"));
    try std.testing.expect(!isDangerousCFunction("strlen"));
    try std.testing.expect(!isDangerousCFunction("malloc"));
    try std.testing.expect(!isDangerousCFunction("free"));
    try std.testing.expect(!isDangerousCFunction("fgets"));
    try std.testing.expect(!isDangerousCFunction("strncpy"));
    try std.testing.expect(!isDangerousCFunction("strncat"));
}

test "isZigSafeCimport: dangerous functions return false" {
    try std.testing.expect(!isZigSafeCimport("strcpy"));
    try std.testing.expect(!isZigSafeCimport("sprintf"));
    try std.testing.expect(!isZigSafeCimport("gets"));
    try std.testing.expect(!isZigSafeCimport("system"));
    try std.testing.expect(!isZigSafeCimport("printf"));
    try std.testing.expect(!isZigSafeCimport("scanf"));
}

test "isZigSafeCimport: safe functions return true" {
    // Layer 2 (conditional) functions should return false
    try std.testing.expect(!isZigSafeCimport("memcpy"));
    try std.testing.expect(!isZigSafeCimport("snprintf"));
    try std.testing.expect(!isZigSafeCimport("malloc"));
    try std.testing.expect(!isZigSafeCimport("free"));
    try std.testing.expect(!isZigSafeCimport("fgets"));
    try std.testing.expect(!isZigSafeCimport("strncpy"));

    // Layer 3 (safe) functions should return true
    try std.testing.expect(isZigSafeCimport("strlen"));
    try std.testing.expect(isZigSafeCimport("sin"));
    try std.testing.expect(isZigSafeCimport("sqrt"));
}
