const std = @import("std");
const types = @import("types.zig");

pub const layer6_functions = [_]types.FunctionSemantics{
    .{ .pattern = "operator new", .match_type = .contains, .kind = .cpp_allocator, .severity = .high, .consumes_ownership = false, .transfers_ownership = true, .requires_null_check = false, .requires_taint_check = false, .description = "C++ new - allocates memory, caller must delete" },
    .{ .pattern = "operator new[]", .match_type = .contains, .kind = .cpp_allocator, .severity = .high, .consumes_ownership = false, .transfers_ownership = true, .requires_null_check = false, .requires_taint_check = false, .description = "C++ new[] - array allocation, caller must delete[]" },
    .{ .pattern = "operator delete", .match_type = .contains, .kind = .cpp_allocator, .severity = .high, .consumes_ownership = true, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ delete - frees memory, consumes ownership" },
    .{ .pattern = "operator delete[]", .match_type = .contains, .kind = .cpp_allocator, .severity = .high, .consumes_ownership = true, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ delete[] - frees array memory, consumes ownership" },
    .{ .pattern = "make_unique", .match_type = .contains, .kind = .cpp_allocator, .severity = .medium, .consumes_ownership = false, .transfers_ownership = true, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::make_unique - creates unique_ptr, automatic ownership" },
    .{ .pattern = "make_shared", .match_type = .contains, .kind = .cpp_allocator, .severity = .medium, .consumes_ownership = false, .transfers_ownership = true, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::make_shared - creates shared_ptr, automatic ownership" },
    .{ .pattern = "unique_ptr", .match_type = .contains, .kind = .cpp_allocator, .severity = .medium, .consumes_ownership = false, .transfers_ownership = true, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::unique_ptr - exclusive ownership, auto-release" },
    .{ .pattern = "shared_ptr", .match_type = .contains, .kind = .cpp_allocator, .severity = .medium, .consumes_ownership = false, .transfers_ownership = true, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::shared_ptr - shared ownership, ref-counted" },
    .{ .pattern = "weak_ptr", .match_type = .contains, .kind = .borrow_escaped, .severity = .medium, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = true, .requires_taint_check = false, .description = "C++ std::weak_ptr - non-owning reference, lock for access" },
    .{ .pattern = "std::move", .match_type = .contains, .kind = .rust_ownership, .severity = .medium, .consumes_ownership = false, .transfers_ownership = true, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::move - transfers ownership (move semantics)" },
    .{ .pattern = "std::forward", .match_type = .contains, .kind = .borrow_escaped, .severity = .low, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::forward - perfect forwarding, preserves value category" },
    .{ .pattern = "std::malloc", .match_type = .contains, .kind = .allocator, .severity = .medium, .consumes_ownership = false, .transfers_ownership = true, .requires_null_check = true, .requires_taint_check = false, .description = "C++ std::malloc - C allocation, requires free" },
    .{ .pattern = "std::free", .match_type = .contains, .kind = .deallocator, .severity = .high, .consumes_ownership = true, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::free - C deallocation, consumes ownership" },
    .{ .pattern = "std::vector", .match_type = .contains, .kind = .cpp_allocator, .severity = .medium, .consumes_ownership = false, .transfers_ownership = true, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::vector - dynamic array, automatic memory management" },
    .{ .pattern = "std::string", .match_type = .contains, .kind = .cpp_allocator, .severity = .medium, .consumes_ownership = false, .transfers_ownership = true, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::string - string class, automatic memory management" },
    .{ .pattern = "std::array", .match_type = .contains, .kind = .borrow_escaped, .severity = .low, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::array - fixed-size array, stack allocated" },
    .{ .pattern = "std::optional", .match_type = .contains, .kind = .borrow_escaped, .severity = .low, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = true, .requires_taint_check = false, .description = "C++ std::optional - may or may not contain a value" },
    .{ .pattern = "unique_lock", .match_type = .contains, .kind = .borrow_escaped, .severity = .medium, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::unique_lock - RAII lock, auto-release on destruction" },
    .{ .pattern = "lock_guard", .match_type = .contains, .kind = .borrow_escaped, .severity = .medium, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::lock_guard - RAII lock, auto-release on destruction" },
    .{ .pattern = "shared_lock", .match_type = .contains, .kind = .borrow_escaped, .severity = .medium, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::shared_lock - RAII reader lock" },
    .{ .pattern = "std::promise", .match_type = .contains, .kind = .borrow_escaped, .severity = .medium, .consumes_ownership = false, .transfers_ownership = true, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::promise - asynchronous value holder" },
    .{ .pattern = "std::future", .match_type = .contains, .kind = .borrow_escaped, .severity = .medium, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::future - asynchronous result retrieval" },
    .{ .pattern = "packaged_task", .match_type = .contains, .kind = .borrow_escaped, .severity = .medium, .consumes_ownership = false, .transfers_ownership = true, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::packaged_task - asynchronous callable wrapper" },
    .{ .pattern = "std::thread", .match_type = .contains, .kind = .borrow_escaped, .severity = .high, .consumes_ownership = false, .transfers_ownership = true, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::thread - thread of execution, joined or detached" },
    .{ .pattern = "std::bind", .match_type = .contains, .kind = .borrow_escaped, .severity = .low, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::bind - function adapter, binds arguments" },
    .{ .pattern = "std::function", .match_type = .contains, .kind = .borrow_escaped, .severity = .low, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::function - type-erased callable wrapper" },
    .{ .pattern = "std::ref", .match_type = .contains, .kind = .borrow_escaped, .severity = .low, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::ref - reference wrapper for callable" },
    .{ .pattern = "std::mem_fn", .match_type = .contains, .kind = .borrow_escaped, .severity = .low, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::mem_fn - member function adapter" },
    .{ .pattern = "std::placeholders", .match_type = .contains, .kind = .borrow_escaped, .severity = .low, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::placeholders - placeholders for bound arguments" },
    .{ .pattern = "std::unique_function", .match_type = .contains, .kind = .borrow_escaped, .severity = .medium, .consumes_ownership = false, .transfers_ownership = true, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::unique_function - owning function wrapper" },
    .{ .pattern = "std::variant", .match_type = .contains, .kind = .borrow_escaped, .severity = .low, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::variant - type-safe union, requires visitor" },
    .{ .pattern = "std::any", .match_type = .contains, .kind = .borrow_escaped, .severity = .medium, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::any - type-erased container" },
    .{ .pattern = "std::shared_mutex", .match_type = .contains, .kind = .borrow_escaped, .severity = .medium, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::shared_mutex - shared reader-writer lock" },
    .{ .pattern = "std::atomic", .match_type = .contains, .kind = .borrow_escaped, .severity = .medium, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::atomic - atomic operations wrapper" },
    .{ .pattern = "std::scoped_lock", .match_type = .contains, .kind = .borrow_escaped, .severity = .medium, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::scoped_lock - RAII multiple mutex lock" },
    .{ .pattern = "std::deque", .match_type = .contains, .kind = .cpp_allocator, .severity = .medium, .consumes_ownership = false, .transfers_ownership = true, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::deque - double-ended queue" },
    .{ .pattern = "std::list", .match_type = .contains, .kind = .cpp_allocator, .severity = .medium, .consumes_ownership = false, .transfers_ownership = true, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::list - doubly-linked list" },
    .{ .pattern = "std::set", .match_type = .contains, .kind = .cpp_allocator, .severity = .medium, .consumes_ownership = false, .transfers_ownership = true, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::set - ordered set container" },
    .{ .pattern = "std::map", .match_type = .contains, .kind = .cpp_allocator, .severity = .medium, .consumes_ownership = false, .transfers_ownership = true, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::map - ordered key-value container" },
    .{ .pattern = "std::multiset", .match_type = .contains, .kind = .cpp_allocator, .severity = .medium, .consumes_ownership = false, .transfers_ownership = true, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::multiset - ordered set with duplicates" },
    .{ .pattern = "std::multimap", .match_type = .contains, .kind = .cpp_allocator, .severity = .medium, .consumes_ownership = false, .transfers_ownership = true, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::multimap - ordered key-value with duplicates" },
    .{ .pattern = "std::unordered_set", .match_type = .contains, .kind = .cpp_allocator, .severity = .medium, .consumes_ownership = false, .transfers_ownership = true, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::unordered_set - hash set container" },
    .{ .pattern = "std::unordered_map", .match_type = .contains, .kind = .cpp_allocator, .severity = .medium, .consumes_ownership = false, .transfers_ownership = true, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::unordered_map - hash key-value container" },
    .{ .pattern = "std::unordered_multiset", .match_type = .contains, .kind = .cpp_allocator, .severity = .medium, .consumes_ownership = false, .transfers_ownership = true, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::unordered_multiset - hash set with duplicates" },
    .{ .pattern = "std::unordered_multimap", .match_type = .contains, .kind = .cpp_allocator, .severity = .medium, .consumes_ownership = false, .transfers_ownership = true, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::unordered_multimap - hash key-value with duplicates" },
    .{ .pattern = "std::stack", .match_type = .contains, .kind = .cpp_allocator, .severity = .low, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::stack - LIFO container adapter" },
    .{ .pattern = "std::queue", .match_type = .contains, .kind = .cpp_allocator, .severity = .low, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::queue - FIFO container adapter" },
    .{ .pattern = "std::priority_queue", .match_type = .contains, .kind = .cpp_allocator, .severity = .low, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::priority_queue - heap-based priority queue" },
    .{ .pattern = "std::tuple", .match_type = .contains, .kind = .borrow_escaped, .severity = .low, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::tuple - fixed-size heterogeneous container" },
    .{ .pattern = "std::pair", .match_type = .contains, .kind = .borrow_escaped, .severity = .low, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::pair - two-element container" },
    .{ .pattern = "std::span", .match_type = .contains, .kind = .borrow_escaped, .severity = .low, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::span - non-owning view of a contiguous sequence" },
    .{ .pattern = "std::view", .match_type = .contains, .kind = .borrow_escaped, .severity = .low, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::view - non-owning view adapters" },
    .{ .pattern = "std::byte", .match_type = .contains, .kind = .borrow_escaped, .severity = .low, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::byte - byte type for memory representation" },
    .{ .pattern = "std::bitset", .match_type = .contains, .kind = .borrow_escaped, .severity = .low, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::bitset - fixed-size bitset" },
    .{ .pattern = "std::typeindex", .match_type = .contains, .kind = .borrow_escaped, .severity = .low, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::typeindex - runtime type information wrapper" },
    .{ .pattern = "std::typeinfo", .match_type = .contains, .kind = .borrow_escaped, .severity = .low, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::typeinfo - type information wrapper" },
    .{ .pattern = "std::initializer_list", .match_type = .contains, .kind = .borrow_escaped, .severity = .low, .consumes_ownership = false, .transfers_ownership = false, .requires_null_check = false, .requires_taint_check = false, .description = "C++ std::initializer_list - initializer list wrapper" },
};

test "layer6_reg: function count" {
    try std.testing.expectEqual(@as(usize, 57), layer6_functions.len);
}

test "layer6_reg: operator new/delete pairs" {
    inline for (layer6_functions) |entry| {
        const name = @as([]const u8, entry.pattern);
        if (std.mem.indexOf(u8, name, "operator new") != null) {
            try std.testing.expectEqual(@as(bool, true), entry.transfers_ownership);
        }
        if (std.mem.indexOf(u8, name, "operator delete") != null) {
            try std.testing.expectEqual(@as(bool, true), entry.consumes_ownership);
        }
    }
}

test "layer6_reg: smart pointers transfer ownership" {
    inline for (layer6_functions) |entry| {
        const name = @as([]const u8, entry.pattern);
        if (std.mem.indexOf(u8, name, "unique_ptr") != null or std.mem.indexOf(u8, name, "shared_ptr") != null or std.mem.indexOf(u8, name, "make_unique") != null or std.mem.indexOf(u8, name, "make_shared") != null) {
            try std.testing.expectEqual(@as(bool, true), entry.transfers_ownership);
        }
    }
}
