//! Go (cgo) FFI Adapter — Handles Go's cgo interop patterns.
//!
//! Key Go FFI concepts modeled here:
//!
//!   - **defer mechanism**: Cleanup scheduled at function end (defer C.free(ptr))
//!     This is Go's closest analog to RAII — resources are guaranteed to be
//!     cleaned up when the function returns, even on panic paths.
//!
//!   - **runtime.SetFinalizer**: Similar to C++ destructors or Java finalizers.
//!     The GC calls the registered function when an object is collected.
//!     Not deterministic — can't rely on it for timely resource release.
//!
//!   - **cgo wrapper functions** (_Cgo_*): Generated by the cgo tool to bridge
//!     between Go calling conventions and C ABI. These are the actual FFI
//!     boundary points in compiled Go code.
//!
//!   - **Go runtime manages goroutine stack**: Go pointers passed to C must
//!     not contain Go pointers themselves (the "Go pointer passing rules").
//!     Violations cause runtime crashes, not just memory corruption.
//!
//! ## Reference
//!   - https://go.dev/cmd/cgo/ (cgo command documentation)
//!   - TinyGo IR spec: docs/en/ir-specs/TINYGO_IR_SPEC.md

const std = @import("std");
const adapter_mod = @import("language_adapter.zig");
const types = @import("types.zig");
const FFISemantics = types.FFISemantics;
const Language = types.Language;
const c = @cImport({
    @cInclude("llvm-c/Core.h");
});

// ═══════════════════════════════════════════════════════════════
// Pattern Tables
// ═══════════════════════════════════════════════════════════════

/// Go runtime functions that should be suppressed from analysis.
///
/// These are compiler-generated or runtime-internal functions that don't
/// represent real FFI boundaries. They're part of Go's runtime system
/// for GC, scheduling, and goroutine management.
pub const RUNTIME_FUNCTIONS = [_][]const u8{
    // Memory allocation (GC-managed) - Go standard compiler
    "runtime.mallocgc",
    "runtime.newobject",
    // Memory allocation - TinyGo compiler
    "runtime.alloc",
    "runtime.free",
    "runtime.realloc",
    // Slice / map / channel construction
    "runtime.makeslice",
    "runtime.makemap",
    "runtime.makechan",
    // Stack management
    "runtime.morestack",
    "runtime.lessstack",
    "runtime.morestack_noctxt",
    // Scheduler
    "runtime.gopanic",
    "runtime.goPanicIndex",
    "runtime.goPanicSliceU",
    "runtime.goPanicSliceB",
    "runtime.throw",
    "runtime.fatal",
    // Defer handling
    "runtime.deferreturn",
    "runtime.deferproc",
    "runtime.deferprocStack",
    // Recovery
    "runtime.recovery",
    "runtime.gorecover",
    // Interface / type checks
    "runtime.assertI2I",
    "runtime.assertE2I",
    "runtime.assertI2E",
    "runtime.convI2E",
    "runtime.convE2I",
    // GC internals
    "runtime.gcStart",
    "runtime.gcDrain",
    "runtime.gcSweep",
    "runtime.gcBgMarkWorker",
    // TinyGo-specific runtime functions
    "runtime._panic",
    "runtime._recover",
    "runtime.trackPointer",
    "runtime.setupDeferFrame",
    "runtime.destroyDeferFrame",
    "runtime.chanMake",
    "runtime.chanSend",
    "runtime.chanRecv",
    "runtime.chanClose",
    "runtime.hashmapMakeGeneric",
    "runtime.stringConcat",
    "runtime.typeAssert",
    "runtime.sliceAppend",
    // Write barriers (GC safety)
    "runtime.writeBarrier",
    "runtime.cgoCheckPointer",
    "runtime.cgoCheckResult",
};

/// Prefix for cgo-generated wrapper functions.
///
/// The cgo tool generates these bridge functions automatically:
///   - _Cgo_malloc → wraps C malloc with Go calling convention
///   - _Cgo_free  → wraps C free
///   - _Cgo_ptr   → pointer conversion helpers
pub const CGO_WRAPPER_PREFIX = "_Cgo_";

/// Additional cgo-related function prefixes/patterns beyond _Cgo_*.
pub const CGO_PATTERNS = [_][]const u8{
    "_cgo_",
    "_Cfunc_",
    "_Ctype_",
    "crosscall2", // Runtime cross-call bridge
    "runtime.cgocall",
    "unionfield_", // TinyGo union field access
    "bitfield_", // TinyGo bitfield access
};

/// Common C standard library calls wrapped by Go via cgo.
///
/// When Go code calls C.malloc / C.free etc., the compiler generates
/// a _Cgo_* wrapper. These are the underlying C functions that the
/// wrappers delegate to.
pub const C_STDLIB_WRAPPERS = [_][]const u8{
    "C.malloc",
    "C.calloc",
    "C.realloc",
    "C.free",
    "C.strdup",
    "C.getenv",
    "C.setenv",
    "C.fopen",
    "C.fclose",
    "C.memcpy",
    "C.memset",
};

/// Go-specific cgo string/bytes conversion functions.
///
/// These functions are part of Go's cgo package and handle conversion
/// between Go types (string, []byte) and C types (char*, void*).
/// They are common sources of memory safety issues at FFI boundaries.
pub const CGO_CONVERSION_FUNCTIONS = [_][]const u8{
    // Go → C conversions (allocate C memory)
    "C.CString", // Go string → C char* (must call C.free)
    "C.CBytes", // Go []byte → C void* (must call C.free)
    // C → Go conversions (borrow C memory)
    "C.GoString", // C char* → Go string (borrows, don't free)
    "C.GoStringN", // C char* + length → Go string (borrows, don't free)
    "C.GoBytes", // C void* + length → Go []byte (copies, don't free result)
};

/// Common syscall wrappers used by Go programs.
pub const SYSCALL_WRAPPERS = [_][]const u8{
    "Syscall.open",
    "Syscall.read",
    "Syscall.write",
    "Syscall.close",
    "Syscall.socket",
    "Syscall.connect",
    "Syscall.bind",
    "Syscall.listen",
    "Syscall.accept",
    "Syscall.fork",
    "Syscall.exec",
};

// ═══════════════════════════════════════════════════════════════
// Adapter Implementation
// ═══════════════════════════════════════════════════════════════

/// Singleton instance of the Go language adapter.
pub const instance = adapter_mod.LanguageAdapter{
    .name = "go",
    .language = .go,
    .memory_model = .hybrid,
    .vtable = .{
        .analyzeFn = analyzeFunction,
        .classifyFn = classifyCall,
        .suppressFn = shouldSuppress,
        .owningPatternsFn = getOwningPatterns,
        .borrowingPatternsFn = getBorrowingPatterns,
    },
};

/// Classify a Go/cgo FFI call by callee name.
///
/// Go's model is different from Python:
///   - C.malloc / C.calloc → returns_owned (caller gets raw C heap pointer)
///   - C.free → consumes_arg (takes ownership of C heap pointer)
///   - C.CString / C.CBytes → returns_owned (allocates C memory, needs C.free)
///   - runtime.* → suppressed (not real FFI)
///   - _Cgo_* → wrapper boundary (depends on wrapped function)
pub fn classifyCall(
    self_ptr: *const adapter_mod.LanguageAdapter,
    callee_name: []const u8,
) FFISemantics {
    _ = self_ptr;

    // Go cgo conversion functions (high-value targets for FFI analysis)
    for (CGO_CONVERSION_FUNCTIONS) |f| {
        if (std.mem.eql(u8, callee_name, f)) {
            // CString/CBytes allocate C memory that must be freed
            if (std.mem.indexOf(u8, callee_name, "CString") != null or
                std.mem.indexOf(u8, callee_name, "CBytes") != null)
            {
                return .returns_owned;
            }
            // GoString/GoStringN/GoBytes borrow or copy C memory
            return .returns_borrowed;
        }
    }

    // C allocation wrappers return owned C pointers
    for (C_STDLIB_WRAPPERS) |f| {
        if (std.mem.eql(u8, callee_name, f)) {
            // C.free consumes; others return owned
            if (std.mem.indexOf(u8, callee_name, ".free") != null) {
                return .consumes_arg;
            }
            if (std.mem.indexOf(u8, callee_name, ".malloc") != null or
                std.mem.indexOf(u8, callee_name, ".calloc") != null or
                std.mem.indexOf(u8, callee_name, ".realloc") != null or
                std.mem.indexOf(u8, callee_name, ".strdup") != null)
            {
                return .returns_owned;
            }
            return .unknown;
        }
    }

    // cgo wrappers: classify based on what they wrap
    if (isCGoWrapper(callee_name)) {
        if (std.mem.indexOf(u8, callee_name, "free") != null) return .consumes_arg;
        if (std.mem.indexOf(u8, callee_name, "malloc") != null) return .returns_owned;
        return .unknown;
    }

    return .unknown;
}

/// Check if a function should be suppressed from FFI analysis.
///
/// Go runtime internal functions (runtime.*) and cgo infrastructure
/// should not be treated as FFI boundaries. Only user-level C calls
/// through cgo are real boundaries.
pub fn shouldSuppress(
    self_ptr: *const adapter_mod.LanguageAdapter,
    func_name: []const u8,
) bool {
    _ = self_ptr;

    // Suppress all runtime.* functions
    if (isRuntimeFunction(func_name)) return true;

    // Suppress known runtime-adjacent prefixes
    const suppress_prefixes = [_][]const u8{
        "runtime.",
        "internal/abi.",
        "internal/task.",
        "internal/runtime/", // TinyGo internal runtime
        "reflect.", // Go reflection (compiler-generated)
    };
    for (suppress_prefixes) |prefix| {
        if (std.mem.startsWith(u8, func_name, prefix)) return true;
    }

    // Suppress compiler-generated symbols
    const compiler_patterns = [_][]const u8{
        "go:", // Reserved import prefix
        "type:", // Type descriptor prefix
        ".inittask", // Init task records
        "type:.hash", // Type hash functions
        "type:.eq", // Type equality functions
        "type:.kind", // Type kind functions
        "go:itab.", // Interface tables
        "__cgo_", // Cgo static references
        "gc.stackobject", // GC stack objects (TinyGo)
        "stackalloc", // Stack allocation (TinyGo)
    };
    for (compiler_patterns) |pattern| {
        if (std.mem.indexOf(u8, func_name, pattern) != null) return true;
    }

    return false;
}

/// Return owning pattern list for Go: C allocators.
pub fn getOwningPatterns(self_ptr: *const adapter_mod.LanguageAdapter) []const []const u8 {
    _ = self_ptr;
    return &C_STDLIB_WRAPPERS;
}

/// Return borrowing pattern list for Go: mostly empty since Go/C borrows rarely.
pub fn getBorrowingPatterns(self_ptr: *const adapter_mod.LanguageAdapter) []const []const u8 {
    _ = self_ptr;
    return &[_][]const u8{};
}

/// Full LLVM IR analysis of a Go function's FFI calls.
///
/// Similar to Python adapter, this is a placeholder that returns metadata
/// without full IR walking. The classifyCall() method provides the practical
/// per-call classification.
pub fn analyzeFunction(
    self_ptr: *const adapter_mod.LanguageAdapter,
    func_opaque: *anyopaque,
    ctx: adapter_mod.ContextPtr,
    allocator: std.mem.Allocator,
) !types.AdapterAnalysis {
    _ = ctx;

    var result = try types.AdapterAnalysis.init(allocator, self_ptr.language);
    errdefer result.deinit();

    const llvm_func: c.LLVMValueRef = @ptrCast(@alignCast(func_opaque));

    if (c.LLVMIsDeclaration(llvm_func) != 0) {
        result.confidence = 0.1;
        return result;
    }

    var bb_iter = c.LLVMGetFirstBasicBlock(llvm_func);

    while (bb_iter != null) : (bb_iter = c.LLVMGetNextBasicBlock(bb_iter)) {
        const bb = bb_iter.?;

        var inst_iter = c.LLVMGetFirstInstruction(bb);

        while (inst_iter != null) : (inst_iter = c.LLVMGetNextInstruction(inst_iter)) {
            const inst = inst_iter.?;

            const opcode = c.LLVMGetInstructionOpcode(inst);
            if (opcode != c.LLVMCall) continue;

            const called_value = c.LLVMGetCalledValue(inst);
            if (called_value == null) continue;

            const callee_name_ptr = c.LLVMGetValueName(called_value);
            if (callee_name_ptr == null) continue;
            const callee_name = std.mem.span(callee_name_ptr);

            const classification = classifyCall(self_ptr, callee_name);

            if (classification == .unknown) continue;

            const inst_addr: u64 = @intFromPtr(inst);

            // Use tiered confidence calibration (T2b FP tuning)
            const call_confidence = calcTieredConfidence(callee_name, classification);
            const call_info = types.FFICallInfo.init(
                inst_addr,
                callee_name,
                classification,
                call_confidence,
                .go,
            );

            try result.addCall(call_info);

            if (classification == .returns_owned) {
                result.refcount_increments += 1;
            } else if (classification == .consumes_arg) {
                result.refcount_decrements += 1;
            }
        }
    }

    result.refcount_balance = @as(i32, @intCast(result.refcount_increments)) -
        @as(i32, @intCast(result.refcount_decrements));

    if (result.refcount_balance > 0) {
        result.has_potential_leak = true;
        result.leak_severity = if (result.refcount_balance > 2) .high else .medium;
    }

    // ═══════════════════════════════════════════════════════════
    // Memory Safety: malloc/free pairing detection
    // ═══════════════════════════════════════════════════════════
    // Track allocation/deallocation pairing for cgo FFI calls.
    // This implements single-function scope analysis as specified in
    // docs/v2/ffi_lang_support_plan.md Phase 1.
    var unpaired_allocs = std.ArrayList(types.FFICallInfo){};
    defer unpaired_allocs.deinit(allocator);

    for (result.ffi_calls.items) |call| {
        const callee_name = call.callee_name;

        if (isCgoAllocFunction(callee_name)) {
            try unpaired_allocs.append(allocator, call);
        }

        if (isCgoFreeFunction(callee_name)) {
            if (unpaired_allocs.items.len > 0) {
                _ = unpaired_allocs.pop();
            }
        }
    }

    // Report memory leaks for unpaired allocations
    for (unpaired_allocs.items) |alloc_call| {
        const func_name_ptr = c.LLVMGetValueName(llvm_func);
        const func_name_slice = if (func_name_ptr) |ptr|
            std.mem.span(ptr)
        else
            "unknown";

        const msg = try std.fmt.allocPrint(
            allocator,
            "[Go cgo] Memory leak: {s}() at instruction 0x{x} has no matching free in function '{s}'",
            .{ alloc_call.callee_name, alloc_call.inst_addr, func_name_slice },
        );

        const issue_confidence = calcTieredConfidenceForIssue(alloc_call.callee_name, .memory_leak);
        const issue = types.AdapterIssue{
            .issue_type = .memory_leak,
            .message = msg,
            .location = types.IssueLocation.initWithAddr(func_name_slice, alloc_call.inst_addr),
            .severity = if (unpaired_allocs.items.len > 2) .high else .medium,
            .confidence = issue_confidence,
            .evidence = "cgo alloc/free pairing analysis",
        };

        try result.addIssue(issue);

        const log = std.log.scoped(.go_adapter);
        log.debug("DETECTED LEAK: {s} at 0x{x} in '{s}' (confidence={d:.2})", .{
            alloc_call.callee_name,
            alloc_call.inst_addr,
            func_name_slice,
            issue.confidence,
        });
    }

    result.is_analyzed = true;
    result.confidence = if (result.ffi_calls.items.len > 0) GoConfidence.default_go else 0.15;

    // Get function name for logging
    const defer_func_name_ptr = c.LLVMGetValueName(llvm_func);
    const defer_func_name = if (defer_func_name_ptr) |ptr|
        std.mem.span(ptr)
    else
        "unknown";

    // ═══════════════════════════════════════════════════════════
    // Defer Pattern Detection (T2a FP Reduction)
    // ═══════════════════════════════════════════════════════════
    // Detect runtime.deferreturn calls which indicate deferred cleanup.
    // In Go, `defer C.free(ptr)` appears at function end in IR as:
    //   1. runtime.deferproc (schedules the deferred call)
    //   2. runtime.deferreturn (executes deferred calls on exit)
    // This pattern causes FP because the actual free happens outside
    // our single-function analysis scope.
    if (hasDeferPattern(llvm_func)) {
        const log = std.log.scoped(.go_adapter);
        log.debug("DEFER PATTERN DETECTED: reducing confidence by 30% for '{s}'", .{
            defer_func_name,
        });
        result.confidence *= 0.7;

        // Also reduce issue confidence for existing issues
        for (result.issues.items) |*issue| {
            issue.confidence *= 0.7;
        }
    }

    return result;
}

/// Detect if a function name is a cgo-generated wrapper.
///
/// The cgo tool generates wrapper functions with the _Cgo_ prefix
/// to bridge Go and C calling conventions. These are the primary
/// FFI boundary indicators in compiled Go code.
pub fn isCGoWrapper(func_name: []const u8) bool {
    if (std.mem.startsWith(u8, func_name, CGO_WRAPPER_PREFIX)) return true;
    for (CGO_PATTERNS) |pattern| {
        if (std.mem.indexOf(u8, func_name, pattern) != null) return true;
    }
    return false;
}

/// Detect if a function is a Go runtime internal function.
///
/// Checks against the comprehensive RUNTIME_FUNCTIONS table plus
/// the broad "runtime." prefix catch-all for any runtime function
/// not explicitly listed.
pub fn isRuntimeFunction(func_name: []const u8) bool {
    // Check explicit table first
    for (RUNTIME_FUNCTIONS) |f| {
        if (std.mem.indexOf(u8, func_name, f) != null) return true;
    }

    // Broad prefix check for runtime package functions
    if (std.mem.startsWith(u8, func_name, "runtime.")) return true;

    return false;
}

/// Check if a function looks like a deferred cleanup call.
///
/// In Go, `defer C.free(ptr)` is the standard pattern for ensuring
/// C-allocated memory is released. These functions typically appear
/// in defer blocks and are called at function exit.
pub fn isLikelyDeferredCleanup(func_name: []const u8) bool {
    // C.* prefixed functions in defer context
    if (std.mem.startsWith(u8, func_name, "C.")) return true;
    // Common cleanup names
    if (std.mem.eql(u8, func_name, "close")) return true;
    if (std.mem.eql(u8, func_name, "destroy")) return true;
    return false;
}

/// Detect cross-language free pattern: Go allocator + C deallocator.
///
/// This is a common source of memory safety bugs in Go cgo code:
///   - runtime.mallocgc (Go GC heap) + free (C) → undefined behavior
///   - _cgo_allocate (Go) + free (C) → cross-language free
///   - C.CString (Go-allocated C memory) correctly freed by C.free ✓
pub fn isCrossLanguageFreePattern(go_alloc: []const u8, c_free: []const u8) bool {
    const go_allocators = [_][]const u8{
        "runtime.mallocgc",
        "runtime.newobject",
        "_cgo_allocate",
        "_Cfunc_GoMalloc",
        "runtime.alloc", // TinyGo
    };

    const c_deallocators = [_][]const u8{
        "free",
        "C.free",
        "_cgo_free",
        "_Cgo_free",
        "_Cfunc_GoFree",
    };

    var is_go_alloc = false;
    for (go_allocators) |alloc| {
        if (std.mem.indexOf(u8, go_alloc, alloc) != null) {
            is_go_alloc = true;
            break;
        }
    }

    var is_c_free = false;
    for (c_deallocators) |dealloc| {
        if (std.mem.indexOf(u8, c_free, dealloc) != null) {
            is_c_free = true;
            break;
        }
    }

    return is_go_alloc and is_c_free;
}

/// Detect potential memory leak pattern: C allocation without matching free.
///
/// Common in Go cgo when:
///   - C.CString / C.CBytes allocated but result discarded or leaked
///   - C.malloc called but C.free never called on the result
///   - Return value from owning function escapes without cleanup
pub fn isPotentialLeakPattern(alloc_call: []const u8, has_matching_free: bool) bool {
    const owning_calls = [_][]const u8{
        "C.CString",
        "C.CBytes",
        "C.malloc",
        "C.calloc",
        "C.strdup",
        "_Cgo_malloc",
    };

    var is_owning = false;
    for (owning_calls) |call| {
        if (std.mem.indexOf(u8, alloc_call, call) != null) {
            is_owning = true;
            break;
        }
    }

    return is_owning and !has_matching_free;
}

// ═══════════════════════════════════════════════════════════════
// Confidence Calibration — Tiered confidence based on call type
// ═══════════════════════════════════════════════════════════════

/// Confidence levels for different FFI call types in Go cgo.
///
/// These values are calibrated based on false positive analysis:
///   - Lower confidence for patterns that may have legitimate explanations
///   - Higher confidence for patterns that almost always indicate bugs
///
/// Reference: T2b FP tuning specification
pub const GoConfidence = struct {
    /// Default confidence for well-classified calls
    pub const default_go: f32 = 0.88;

    /// Malloc/free pairing imbalance (may be freed in another function or deferred)
    pub const malloc_free_imbalance: f32 = 0.85;

    /// CString/CBytes without free (Go often uses defer C.free())
    pub const cstring_no_free: f32 = 0.75;

    /// JNI NewGlobalRef without DeleteGlobalRef (almost certainly a leak)
    pub const jni_globalref_leak: f32 = 0.90;
};

/// Calculate tiered confidence for a Go/cgo FFI call based on callee name and classification.
///
/// This function implements the T2b FP tuning specification by returning
/// different confidence values depending on the call type:
///
///   - **malloc/free imbalance**: 0.85 (uncertain about cross-function free)
///   - **CString without free**: 0.75 (Go may use defer cleanup)
///   - **JNI GlobalRef leak**: 0.90 (nearly always a bug)
///   - **Other calls**: 0.88 (default, maintains current behavior)
///
/// Arguments:
///
///   callee_name - The name of the called function (e.g., "C.malloc", "C.CString")
///   classification - The FFISemantics classification of the call
///
/// Returns:
///
///   Calibrated confidence value between 0.0 and 1.0
///
/// Example:
///
///   ```zig
///   const conf = calcTieredConfidence("C.malloc", .returns_owned);
///   // conf == 0.88 (default for standard allocators)
///
///   const conf_leak = calcTieredConfidenceForIssue("C.CString", .memory_leak);
///   // conf_leak == 0.75 (lower confidence due to defer pattern)
///   ```
pub fn calcTieredConfidence(callee_name: []const u8, classification: FFISemantics) f32 {
    // CString/CBytes: lower confidence because Go often uses `defer C.free(ptr)`
    if (std.mem.indexOf(u8, callee_name, "CString") != null or
        std.mem.indexOf(u8, callee_name, "CBytes") != null)
    {
        return GoConfidence.cstring_no_free;
    }

    // Standard C allocators (malloc, calloc, etc.) use default confidence
    if (classification == .returns_owned) {
        return GoConfidence.default_go;
    }

    // Free/deallocation functions use default confidence
    if (classification == .consumes_arg) {
        return GoConfidence.default_go;
    }

    return GoConfidence.default_go;
}

/// Calculate confidence for memory safety issues based on issue type.
///
/// This provides finer-grained confidence calibration for detected issues,
/// distinguishing between different classes of problems:
///
///   - **Memory leaks from malloc/free**: 0.85 (may be cross-function)
///   - **Leaks from CString**: 0.75 (defer cleanup common)
///   - **JNI leaks**: 0.90 (almost always bugs)
///   - **Other issues**: Uses default value from caller
///
/// Arguments:
///
///   callee_name - The function that triggered the issue detection
///   issue_type - The type of issue detected
///
/// Returns:
///
///   Calibrated confidence value for the specific issue pattern
pub fn calcTieredConfidenceForIssue(callee_name: []const u8, issue_type: types.AdapterIssueType) f32 {
    switch (issue_type) {
        .memory_leak => {
            // CString/CBytes leaks get lower confidence (defer pattern)
            if (std.mem.indexOf(u8, callee_name, "CString") != null or
                std.mem.indexOf(u8, callee_name, "CBytes") != null)
            {
                return GoConfidence.cstring_no_free;
            }
            // Standard malloc/free imbalance
            return GoConfidence.malloc_free_imbalance;
        },
        else => return GoConfidence.default_go,
    }
}

// ═══════════════════════════════════════════════════════════════
// Memory Safety Detection Helpers
// ═══════════════════════════════════════════════════════════════

/// Re-export AdapterIssueType from types.zig for convenience.
pub const AdapterIssueType = types.AdapterIssueType;

/// Check if callee is a known cgo allocation function.
///
/// These functions allocate C heap memory that must be explicitly freed:
///   - C.malloc / C.calloc / C.strdup: Standard C allocators
///   - C.CString / C.CBytes: Go→C conversion functions (call malloc internally)
///   - _cgo_allocate / _Cfunc_GoMalloc: cgo-generated wrappers
pub fn isCgoAllocFunction(callee_name: []const u8) bool {
    const CGO_ALLOC_FUNCTIONS = [_][]const u8{
        "C.malloc",
        "C.calloc",
        "C.strdup",
        "C.CString",
        "C.CBytes",
        "_cgo_allocate",
        "_Cgo_malloc",
        "_Cfunc_GoMalloc",
    };

    for (CGO_ALLOC_FUNCTIONS) |pattern| {
        if (std.mem.indexOf(u8, callee_name, pattern) != null) {
            return true;
        }
    }
    return false;
}

/// Check if callee is a known cgo deallocation function.
///
/// These functions release C heap memory:
///   - C.free: Standard C deallocator
///   - _cgo_free / _Cgo_free / _Cfunc_GoFree: cgo-generated wrappers
pub fn isCgoFreeFunction(callee_name: []const u8) bool {
    const CGO_FREE_FUNCTIONS = [_][]const u8{
        "C.free",
        "_cgo_free",
        "_Cgo_free",
        "_Cfunc_GoFree",
    };

    for (CGO_FREE_FUNCTIONS) |pattern| {
        if (std.mem.indexOf(u8, callee_name, pattern) != null) {
            return true;
        }
    }
    return false;
}

/// Detect if a Go function uses the defer mechanism for cleanup.
///
/// This function scans the LLVM IR for runtime.deferreturn calls,
/// which are generated by the Go compiler when `defer` statements
/// are present in the source code.
///
/// Why this matters for FP reduction:
///   - In Go, `defer C.free(ptr)` schedules cleanup at function exit
///   - The actual free call happens via runtime.deferreturn at the end
///   - Our single-function analysis sees the alloc but may miss the
///     deferred free (it's not a direct call in the normal flow)
///   - This causes false positive leak reports
///
/// Returns true if defer pattern is detected, false otherwise.
///
/// Example IR pattern:
///   ```llvm
///   %0 = call i8* @runtime.deferproc(i32 0)
///   ... function body ...
///   call void @runtime.deferreturn()
///   ```
pub fn hasDeferPattern(llvm_func: c.LLVMValueRef) bool {
    // Check if this is a declaration (no body to analyze)
    if (c.LLVMIsDeclaration(llvm_func) != 0) return false;

    var bb_iter = c.LLVMGetFirstBasicBlock(llvm_func);

    while (bb_iter != null) : (bb_iter = c.LLVMGetNextBasicBlock(bb_iter)) {
        const bb = bb_iter.?;

        var inst_iter = c.LLVMGetFirstInstruction(bb);

        while (inst_iter != null) : (inst_iter = c.LLVMGetNextInstruction(inst_iter)) {
            const inst = inst_iter.?;

            // Only check call instructions
            const opcode = c.LLVMGetInstructionOpcode(inst);
            if (opcode != c.LLVMCall) continue;

            const called_value = c.LLVMGetCalledValue(inst);
            if (called_value == null) continue;

            const callee_name_ptr = c.LLVMGetValueName(called_value);
            if (callee_name_ptr == null) continue;
            const callee_name = std.mem.span(callee_name_ptr);

            // Check for defer-related runtime calls
            if (std.mem.eql(u8, callee_name, "runtime.deferreturn") or
                std.mem.eql(u8, callee_name, "runtime.deferproc") or
                std.mem.eql(u8, callee_name, "runtime.deferprocStack"))
            {
                return true;
            }
        }
    }

    return false;
}
