//! Go (cgo) FFI Adapter — Handles Go's cgo interop patterns.
//!
//! Key Go FFI concepts modeled here:
//!
//!   - **defer mechanism**: Cleanup scheduled at function end (defer C.free(ptr))
//!     This is Go's closest analog to RAII — resources are guaranteed to be
//!     cleaned up when the function returns, even on panic paths.
//!
//!   - **runtime.SetFinalizer**: Similar to C++ destructors or Java finalizers.
//!     The GC calls the registered function when an object is collected.
//!     Not deterministic — can't rely on it for timely resource release.
//!
//!   - **cgo wrapper functions** (_Cgo_*): Generated by the cgo tool to bridge
//!     between Go calling conventions and C ABI. These are the actual FFI
//!     boundary points in compiled Go code.
//!
//!   - **Go runtime manages goroutine stack**: Go pointers passed to C must
//!     not contain Go pointers themselves (the "Go pointer passing rules").
//!     Violations cause runtime crashes, not just memory corruption.
//!
//! ## Reference
//!   - https://go.dev/cmd/cgo/ (cgo command documentation)
//!   - TinyGo IR spec: docs/en/ir-specs/TINYGO_IR_SPEC.md

const std = @import("std");
const adapter_mod = @import("language_adapter.zig");
const types = @import("types.zig");
const FFISemantics = types.FFISemantics;
const Language = types.Language;

// ═══════════════════════════════════════════════════════════════
// Pattern Tables
// ═══════════════════════════════════════════════════════════════

/// Go runtime functions that should be suppressed from analysis.
///
/// These are compiler-generated or runtime-internal functions that don't
/// represent real FFI boundaries. They're part of Go's runtime system
/// for GC, scheduling, and goroutine management.
pub const RUNTIME_FUNCTIONS = [_][]const u8{
    // Memory allocation (GC-managed)
    "runtime.mallocgc",
    "runtime.newobject",
    // Slice / map / channel construction
    "runtime.makeslice",
    "runtime.makemap",
    "runtime.makechan",
    // Stack management
    "runtime.morestack",
    "runtime.lessstack",
    "runtime.morestack_noctxt",
    // Scheduler
    "runtime.gopanic",
    "runtime.goPanicIndex",
    "runtime.goPanicSliceU",
    "runtime.goPanicSliceB",
    "runtime.throw",
    "runtime.fatal",
    // Defer handling
    "runtime.deferreturn",
    "runtime.deferproc",
    "runtime.deferprocStack",
    // Recovery
    "runtime.recovery",
    "runtime.gorecover",
    // Interface / type checks
    "runtime.assertI2I",
    "runtime.assertE2I",
    "runtime.assertI2E",
    "runtime.convI2E",
    "runtime.convE2I",
    // GC internals
    "runtime.gcStart",
    "runtime.gcDrain",
    "runtime.gcSweep",
    "runtime.gcBgMarkWorker",
};

/// Prefix for cgo-generated wrapper functions.
///
/// The cgo tool generates these bridge functions automatically:
///   - _Cgo_malloc → wraps C malloc with Go calling convention
///   - _Cgo_free  → wraps C free
///   - _Cgo_ptr   → pointer conversion helpers
pub const CGO_WRAPPER_PREFIX = "_Cgo_";

/// Additional cgo-related function prefixes/patterns beyond _Cgo_*.
pub const CGO_PATTERNS = [_][]const u8{
    "_cgo_",
    "_Cfunc_",
    "_Ctype_",
    "crosscall2", // Runtime cross-call bridge
    "runtime.cgocall",
    "unionfield_", // TinyGo union field access
    "bitfield_", // TinyGo bitfield access
};

/// Common C standard library calls wrapped by Go via cgo.
///
/// When Go code calls C.malloc / C.free etc., the compiler generates
/// a _Cgo_* wrapper. These are the underlying C functions that the
/// wrappers delegate to.
pub const C_STDLIB_WRAPPERS = [_][]const u8{
    "C.malloc",
    "C.calloc",
    "C.realloc",
    "C.free",
    "C.strdup",
    "C.getenv",
    "C.setenv",
    "C.fopen",
    "C.fclose",
    "C.memcpy",
    "C.memset",
};

/// Common syscall wrappers used by Go programs.
pub const SYSCALL_WRAPPERS = [_][]const u8{
    "Syscall.open",
    "Syscall.read",
    "Syscall.write",
    "Syscall.close",
    "Syscall.socket",
    "Syscall.connect",
    "Syscall.bind",
    "Syscall.listen",
    "Syscall.accept",
    "Syscall.fork",
    "Syscall.exec",
};

// ═══════════════════════════════════════════════════════════════
// Adapter Implementation
// ═══════════════════════════════════════════════════════════════

/// Singleton instance of the Go language adapter.
pub const instance = adapter_mod.LanguageAdapter{
    .name = "go",
    .language = .go,
    .memory_model = .hybrid,
    .vtable = .{
        .analyzeFn = analyzeFunction,
        .classifyFn = classifyCall,
        .suppressFn = shouldSuppress,
        .owningPatternsFn = getOwningPatterns,
        .borrowingPatternsFn = getBorrowingPatterns,
    },
};

/// Classify a Go/cgo FFI call by callee name.
///
/// Go's model is different from Python:
///   - C.malloc / C.calloc → returns_owned (caller gets raw C heap pointer)
///   - C.free → consumes_arg (takes ownership of C heap pointer)
///   - runtime.* → suppressed (not real FFI)
///   - _Cgo_* → wrapper boundary (depends on wrapped function)
pub fn classifyCall(
    self_ptr: *const adapter_mod.LanguageAdapter,
    callee_name: []const u8,
) FFISemantics {
    _ = self_ptr;

    // C allocation wrappers return owned C pointers
    for (C_STDLIB_WRAPPERS) |f| {
        if (std.mem.eql(u8, callee_name, f)) {
            // C.free consumes; others return owned
            if (std.mem.indexOf(u8, callee_name, ".free") != null) {
                return .consumes_arg;
            }
            if (std.mem.indexOf(u8, callee_name, ".malloc") != null or
                std.mem.indexOf(u8, callee_name, ".calloc") != null or
                std.mem.indexOf(u8, callee_name, ".realloc") != null)
            {
                return .returns_owned;
            }
            return .unknown;
        }
    }

    // cgo wrappers: classify based on what they wrap
    if (isCGoWrapper(callee_name)) {
        if (std.mem.indexOf(u8, callee_name, "free") != null) return .consumes_arg;
        if (std.mem.indexOf(u8, callee_name, "malloc") != null) return .returns_owned;
        return .unknown;
    }

    return .unknown;
}

/// Check if a function should be suppressed from FFI analysis.
///
/// Go runtime internal functions (runtime.*) and cgo infrastructure
/// should not be treated as FFI boundaries. Only user-level C calls
/// through cgo are real boundaries.
pub fn shouldSuppress(
    self_ptr: *const adapter_mod.LanguageAdapter,
    func_name: []const u8,
) bool {
    _ = self_ptr;

    // Suppress all runtime.* functions
    if (isRuntimeFunction(func_name)) return true;

    // Suppress known runtime-adjacent prefixes
    const suppress_prefixes = [_][]const u8{
        "runtime.",
        "internal/abi.",
        "internal/task.",
    };
    for (suppress_prefixes) |prefix| {
        if (std.mem.startsWith(u8, func_name, prefix)) return true;
    }

    return false;
}

/// Return owning pattern list for Go: C allocators.
pub fn getOwningPatterns(self_ptr: *const adapter_mod.LanguageAdapter) []const []const u8 {
    _ = self_ptr;
    return &C_STDLIB_WRAPPERS;
}

/// Return borrowing pattern list for Go: mostly empty since Go/C borrows rarely.
pub fn getBorrowingPatterns(self_ptr: *const adapter_mod.LanguageAdapter) []const []const u8 {
    _ = self_ptr;
    return &[_][]const u8{};
}

/// Full LLVM IR analysis of a Go function's FFI calls.
///
/// Similar to Python adapter, this is a placeholder that returns metadata
/// without full IR walking. The classifyCall() method provides the practical
/// per-call classification.
pub fn analyzeFunction(
    self_ptr: *const adapter_mod.LanguageAdapter,
    func_opaque: *anyopaque,
    ctx: adapter_mod.ContextPtr,
    allocator: std.mem.Allocator,
) !types.AdapterAnalysis {
    _ = func_opaque;
    _ = ctx;

    var result = try types.AdapterAnalysis.init(allocator, self_ptr.language);
    errdefer result.deinit();

    result.confidence = 0.80;
    return result;
}

/// Detect if a function name is a cgo-generated wrapper.
///
/// The cgo tool generates wrapper functions with the _Cgo_ prefix
/// to bridge Go and C calling conventions. These are the primary
/// FFI boundary indicators in compiled Go code.
pub fn isCGoWrapper(func_name: []const u8) bool {
    if (std.mem.startsWith(u8, func_name, CGO_WRAPPER_PREFIX)) return true;
    for (CGO_PATTERNS) |pattern| {
        if (std.mem.indexOf(u8, func_name, pattern) != null) return true;
    }
    return false;
}

/// Detect if a function is a Go runtime internal function.
///
/// Checks against the comprehensive RUNTIME_FUNCTIONS table plus
/// the broad "runtime." prefix catch-all for any runtime function
/// not explicitly listed.
pub fn isRuntimeFunction(func_name: []const u8) bool {
    // Check explicit table first
    for (RUNTIME_FUNCTIONS) |f| {
        if (std.mem.indexOf(u8, func_name, f) != null) return true;
    }

    // Broad prefix check for runtime package functions
    if (std.mem.startsWith(u8, func_name, "runtime.")) return true;

    return false;
}

/// Check if a function looks like a deferred cleanup call.
///
/// In Go, `defer C.free(ptr)` is the standard pattern for ensuring
/// C-allocated memory is released. These functions typically appear
/// in defer blocks and are called at function exit.
pub fn isLikelyDeferredCleanup(func_name: []const u8) bool {
    // C.* prefixed functions in defer context
    if (std.mem.startsWith(u8, func_name, "C.")) return true;
    // Common cleanup names
    if (std.mem.eql(u8, func_name, "close")) return true;
    if (std.mem.eql(u8, func_name, "destroy")) return true;
    return false;
}

// ═══════════════════════════════════════════════════════════════
// Tests
// ═══════════════════════════════════════════════════════════════

test "GoAdapter - detects cgo wrappers" {
    try testing.expect(isCGoWrapper("_Cgo_malloc"));
    try testing.expect(isCGoWrapper("_Cgo_free"));
    try testing.expect(isCGoWrapper("_Cgo_ptr"));
    try testing.expect(isCGoWrapper("_cgo_123abc"));
    try testing.expect(isCGoWrapper("_Cfunc_foo"));

    // Not cgo wrappers
    try testing.expect(!isCGoWrapper("malloc"));
    try testing.expect(!isCGoWrapper("runtime.mallocgc"));
    try testing.expect(!isCGoWrapper("main.foo"));
}

test "GoAdapter - detects runtime functions" {
    try testing.expect(isRuntimeFunction("runtime.mallocgc"));
    try testing.expect(isRuntimeFunction("runtime.morestack"));
    try testing.expect(isRuntimeFunction("runtime.gopanic"));
    try testing.expect(isRuntimeFunction("runtime.deferreturn"));
    try testing.expect(isRuntimeFunction("runtime.gcStart"));

    // Not runtime functions
    try testing.expect(!isRuntimeFunction("main.foo"));
    try testing.expect(!isRuntimeFunction("malloc"));
    try testing.expect(!isRuntimeFunction("C.free"));
}

test "GoAdapter - classifies C allocator calls" {
    // C allocators return owned
    try testing.expectEqual(FFISemantics.returns_owned, instance.classifyCall("C.malloc"));
    try testing.expectEqual(FFISemantics.returns_owned, instance.classifyCall("C.calloc"));
    try testing.expectEqual(FFISemantics.returns_owned, instance.classifyCall("C.realloc"));

    // C.free consumes argument
    try testing.expectEqual(FFISemantics.consumes_arg, instance.classifyCall("C.free"));

    // Other C wrappers unknown by default
    try testing.expectEqual(FFISemantics.unknown, instance.classifyCall("C.strdup"));
    try testing.expectEqual(FFISemantics.unknown, instance.classifyCall("C.getenv"));
}

test "GoAdapter - classifies cgo wrapper calls" {
    try testing.expectEqual(FFISemantics.returns_owned, instance.classifyCall("_Cgo_malloc"));
    try testing.expectEqual(FFISemantics.consumes_arg, instance.classifyCall("_Cgo_free"));
    try testing.expectEqual(FFISemantics.unknown, instance.classifyCall("_Cgo_ptr"));
}

test "GoAdapter - suppresses runtime functions" {
    try testing.expect(instance.shouldSuppress("runtime.mallocgc"));
    try testing.expect(instance.shouldSuppress("runtime.gopanic"));
    try testing.expect(instance.shouldSuppress("runtime.gcStart"));
    try testing.expect(instance.shouldSuppress("internal/abi.init"));

    // User code should NOT be suppressed
    try testing.expect(!instance.shouldSuppress("main.foo"));
    try testing.expect(!instance.shouldSuppress("C.malloc"));
    try testing.expect(!instance.shouldSuppress("malloc"));
}

test "GoAdapter - deferred cleanup detection" {
    try testing.expect(isLikelyDeferredCleanup("C.free"));
    try testing.expect(isLikelyDeferredCleanup("C.destroy"));
    try testing.expect(isLikelyDeferredCleanup("close"));

    // Not typical deferred cleanup
    try testing.expect(!isLikelyDeferredCleanup("malloc"));
    try testing.expect(!isLikelyDeferredCleanup("runtime.mallocgc"));
}

test "GoAdapter - instance metadata" {
    try testing.expectEqualStrings("go", instance.name);
    try testing.expectEqual(Language.go, instance.language);
    try testing.expectEqual(types.MemoryModel.hybrid, instance.memory_model);
}

test "GoAdapter - pattern lists" {
    const owning = instance.getOwningPatterns();
    const borrowing = instance.getBorrowingPatterns();

    try testing.expect(owning.len > 0);
    try testing.expect(borrowing.len == 0);

    // Verify C.malloc is in owning patterns
    var found_malloc: bool = false;
    for (owning) |p| {
        if (std.mem.eql(u8, p, "C.malloc")) found_malloc = true;
    }
    try testing.expect(found_malloc);
}

const testing = std.testing;
