//! Go (cgo) FFI Adapter — Handles Go's cgo interop patterns.
//!
//! Key Go FFI concepts modeled here:
//!
//!   - **defer mechanism**: Cleanup scheduled at function end (defer C.free(ptr))
//!     This is Go's closest analog to RAII — resources are guaranteed to be
//!     cleaned up when the function returns, even on panic paths.
//!
//!   - **runtime.SetFinalizer**: Similar to C++ destructors or Java finalizers.
//!     The GC calls the registered function when an object is collected.
//!     Not deterministic — can't rely on it for timely resource release.
//!
//!   - **cgo wrapper functions** (_Cgo_*): Generated by the cgo tool to bridge
//!     between Go calling conventions and C ABI. These are the actual FFI
//!     boundary points in compiled Go code.
//!
//!   - **Go runtime manages goroutine stack**: Go pointers passed to C must
//!     not contain Go pointers themselves (the "Go pointer passing rules").
//!     Violations cause runtime crashes, not just memory corruption.
//!
//! ## Reference
//!   - https://go.dev/cmd/cgo/ (cgo command documentation)
//!   - TinyGo IR spec: docs/en/ir-specs/TINYGO_IR_SPEC.md

const std = @import("std");
const adapter_mod = @import("language_adapter.zig");
const types = @import("types.zig");
const FFISemantics = types.FFISemantics;
const Language = types.Language;
const c = @cImport({
    @cInclude("llvm-c/Core.h");
});

// ═══════════════════════════════════════════════════════════════
// Pattern Tables
// ═══════════════════════════════════════════════════════════════

/// Go runtime functions that should be suppressed from analysis.
///
/// These are compiler-generated or runtime-internal functions that don't
/// represent real FFI boundaries. They're part of Go's runtime system
/// for GC, scheduling, and goroutine management.
pub const RUNTIME_FUNCTIONS = [_][]const u8{
    // Memory allocation (GC-managed) - Go standard compiler
    "runtime.mallocgc",
    "runtime.newobject",
    // Memory allocation - TinyGo compiler
    "runtime.alloc",
    "runtime.free",
    "runtime.realloc",
    // Slice / map / channel construction
    "runtime.makeslice",
    "runtime.makemap",
    "runtime.makechan",
    // Stack management
    "runtime.morestack",
    "runtime.lessstack",
    "runtime.morestack_noctxt",
    // Scheduler
    "runtime.gopanic",
    "runtime.goPanicIndex",
    "runtime.goPanicSliceU",
    "runtime.goPanicSliceB",
    "runtime.throw",
    "runtime.fatal",
    // Defer handling
    "runtime.deferreturn",
    "runtime.deferproc",
    "runtime.deferprocStack",
    // Recovery
    "runtime.recovery",
    "runtime.gorecover",
    // Interface / type checks
    "runtime.assertI2I",
    "runtime.assertE2I",
    "runtime.assertI2E",
    "runtime.convI2E",
    "runtime.convE2I",
    // GC internals
    "runtime.gcStart",
    "runtime.gcDrain",
    "runtime.gcSweep",
    "runtime.gcBgMarkWorker",
    // TinyGo-specific runtime functions
    "runtime._panic",
    "runtime._recover",
    "runtime.trackPointer",
    "runtime.setupDeferFrame",
    "runtime.destroyDeferFrame",
    "runtime.chanMake",
    "runtime.chanSend",
    "runtime.chanRecv",
    "runtime.chanClose",
    "runtime.hashmapMakeGeneric",
    "runtime.stringConcat",
    "runtime.typeAssert",
    "runtime.sliceAppend",
    // Write barriers (GC safety)
    "runtime.writeBarrier",
    "runtime.cgoCheckPointer",
    "runtime.cgoCheckResult",
};

/// Prefix for cgo-generated wrapper functions.
///
/// The cgo tool generates these bridge functions automatically:
///   - _Cgo_malloc → wraps C malloc with Go calling convention
///   - _Cgo_free  → wraps C free
///   - _Cgo_ptr   → pointer conversion helpers
pub const CGO_WRAPPER_PREFIX = "_Cgo_";

/// Additional cgo-related function prefixes/patterns beyond _Cgo_*.
pub const CGO_PATTERNS = [_][]const u8{
    "_cgo_",
    "_Cfunc_",
    "_Ctype_",
    "crosscall2", // Runtime cross-call bridge
    "runtime.cgocall",
    "unionfield_", // TinyGo union field access
    "bitfield_", // TinyGo bitfield access
};

/// Common C standard library calls wrapped by Go via cgo.
///
/// When Go code calls C.malloc / C.free etc., the compiler generates
/// a _Cgo_* wrapper. These are the underlying C functions that the
/// wrappers delegate to.
pub const C_STDLIB_WRAPPERS = [_][]const u8{
    "C.malloc",
    "C.calloc",
    "C.realloc",
    "C.free",
    "C.strdup",
    "C.getenv",
    "C.setenv",
    "C.fopen",
    "C.fclose",
    "C.memcpy",
    "C.memset",
};

/// Go-specific cgo string/bytes conversion functions.
///
/// These functions are part of Go's cgo package and handle conversion
/// between Go types (string, []byte) and C types (char*, void*).
/// They are common sources of memory safety issues at FFI boundaries.
pub const CGO_CONVERSION_FUNCTIONS = [_][]const u8{
    // Go → C conversions (allocate C memory)
    "C.CString", // Go string → C char* (must call C.free)
    "C.CBytes", // Go []byte → C void* (must call C.free)
    // C → Go conversions (borrow C memory)
    "C.GoString", // C char* → Go string (borrows, don't free)
    "C.GoStringN", // C char* + length → Go string (borrows, don't free)
    "C.GoBytes", // C void* + length → Go []byte (copies, don't free result)
};

/// Common syscall wrappers used by Go programs.
pub const SYSCALL_WRAPPERS = [_][]const u8{
    "Syscall.open",
    "Syscall.read",
    "Syscall.write",
    "Syscall.close",
    "Syscall.socket",
    "Syscall.connect",
    "Syscall.bind",
    "Syscall.listen",
    "Syscall.accept",
    "Syscall.fork",
    "Syscall.exec",
};

// ═══════════════════════════════════════════════════════════════
// Adapter Implementation
// ═══════════════════════════════════════════════════════════════

/// Singleton instance of the Go language adapter.
pub const instance = adapter_mod.LanguageAdapter{
    .name = "go",
    .language = .go,
    .memory_model = .hybrid,
    .vtable = .{
        .analyzeFn = analyzeFunction,
        .classifyFn = classifyCall,
        .suppressFn = shouldSuppress,
        .owningPatternsFn = getOwningPatterns,
        .borrowingPatternsFn = getBorrowingPatterns,
    },
};

/// Classify a Go/cgo FFI call by callee name.
///
/// Go's model is different from Python:
///   - C.malloc / C.calloc → returns_owned (caller gets raw C heap pointer)
///   - C.free → consumes_arg (takes ownership of C heap pointer)
///   - C.CString / C.CBytes → returns_owned (allocates C memory, needs C.free)
///   - runtime.* → suppressed (not real FFI)
///   - _Cgo_* → wrapper boundary (depends on wrapped function)
pub fn classifyCall(
    self_ptr: *const adapter_mod.LanguageAdapter,
    callee_name: []const u8,
) FFISemantics {
    _ = self_ptr;

    // Go cgo conversion functions (high-value targets for FFI analysis)
    for (CGO_CONVERSION_FUNCTIONS) |f| {
        if (std.mem.eql(u8, callee_name, f)) {
            // CString/CBytes allocate C memory that must be freed
            if (std.mem.indexOf(u8, callee_name, "CString") != null or
                std.mem.indexOf(u8, callee_name, "CBytes") != null)
            {
                return .returns_owned;
            }
            // GoString/GoStringN/GoBytes borrow or copy C memory
            return .returns_borrowed;
        }
    }

    // C allocation wrappers return owned C pointers
    for (C_STDLIB_WRAPPERS) |f| {
        if (std.mem.eql(u8, callee_name, f)) {
            // C.free consumes; others return owned
            if (std.mem.indexOf(u8, callee_name, ".free") != null) {
                return .consumes_arg;
            }
            if (std.mem.indexOf(u8, callee_name, ".malloc") != null or
                std.mem.indexOf(u8, callee_name, ".calloc") != null or
                std.mem.indexOf(u8, callee_name, ".realloc") != null or
                std.mem.indexOf(u8, callee_name, ".strdup") != null)
            {
                return .returns_owned;
            }
            return .unknown;
        }
    }

    // cgo wrappers: classify based on what they wrap
    if (isCGoWrapper(callee_name)) {
        if (std.mem.indexOf(u8, callee_name, "free") != null) return .consumes_arg;
        if (std.mem.indexOf(u8, callee_name, "malloc") != null) return .returns_owned;
        return .unknown;
    }

    return .unknown;
}

/// Check if a function should be suppressed from FFI analysis.
///
/// Go runtime internal functions (runtime.*) and cgo infrastructure
/// should not be treated as FFI boundaries. Only user-level C calls
/// through cgo are real boundaries.
pub fn shouldSuppress(
    self_ptr: *const adapter_mod.LanguageAdapter,
    func_name: []const u8,
) bool {
    _ = self_ptr;

    // Suppress all runtime.* functions
    if (isRuntimeFunction(func_name)) return true;

    // Suppress known runtime-adjacent prefixes
    const suppress_prefixes = [_][]const u8{
        "runtime.",
        "internal/abi.",
        "internal/task.",
        "internal/runtime/", // TinyGo internal runtime
        "reflect.", // Go reflection (compiler-generated)
    };
    for (suppress_prefixes) |prefix| {
        if (std.mem.startsWith(u8, func_name, prefix)) return true;
    }

    // Suppress compiler-generated symbols
    const compiler_patterns = [_][]const u8{
        "go:", // Reserved import prefix
        "type:", // Type descriptor prefix
        ".inittask", // Init task records
        "type:.hash", // Type hash functions
        "type:.eq", // Type equality functions
        "type:.kind", // Type kind functions
        "go:itab.", // Interface tables
        "__cgo_", // Cgo static references
        "gc.stackobject", // GC stack objects (TinyGo)
        "stackalloc", // Stack allocation (TinyGo)
    };
    for (compiler_patterns) |pattern| {
        if (std.mem.indexOf(u8, func_name, pattern) != null) return true;
    }

    return false;
}

/// Return owning pattern list for Go: C allocators.
pub fn getOwningPatterns(self_ptr: *const adapter_mod.LanguageAdapter) []const []const u8 {
    _ = self_ptr;
    return &C_STDLIB_WRAPPERS;
}

/// Return borrowing pattern list for Go: mostly empty since Go/C borrows rarely.
pub fn getBorrowingPatterns(self_ptr: *const adapter_mod.LanguageAdapter) []const []const u8 {
    _ = self_ptr;
    return &[_][]const u8{};
}

/// Full LLVM IR analysis of a Go function's FFI calls.
///
/// Similar to Python adapter, this is a placeholder that returns metadata
/// without full IR walking. The classifyCall() method provides the practical
/// per-call classification.
pub fn analyzeFunction(
    self_ptr: *const adapter_mod.LanguageAdapter,
    func_opaque: *anyopaque,
    ctx: adapter_mod.ContextPtr,
    allocator: std.mem.Allocator,
) !types.AdapterAnalysis {
    _ = ctx;

    var result = try types.AdapterAnalysis.init(allocator, self_ptr.language);
    errdefer result.deinit();

    const llvm_func: c.LLVMValueRef = @ptrCast(@alignCast(func_opaque));

    if (c.LLVMIsDeclaration(llvm_func) != 0) {
        result.confidence = 0.1;
        return result;
    }

    var bb_iter = c.LLVMGetFirstBasicBlock(llvm_func);

    while (bb_iter != null) : (bb_iter = c.LLVMGetNextBasicBlock(bb_iter)) {
        const bb = bb_iter.?;

        var inst_iter = c.LLVMGetFirstInstruction(bb);

        while (inst_iter != null) : (inst_iter = c.LLVMGetNextInstruction(inst_iter)) {
            const inst = inst_iter.?;

            const opcode = c.LLVMGetInstructionOpcode(inst);
            if (opcode != c.LLVMCall) continue;

            const called_value = c.LLVMGetCalledValue(inst);
            if (called_value == null) continue;

            const callee_name_ptr = c.LLVMGetValueName(called_value);
            if (callee_name_ptr == null) continue;
            const callee_name = std.mem.span(callee_name_ptr);

            const classification = classifyCall(self_ptr, callee_name);

            if (classification == .unknown) continue;

            const inst_addr: u64 = @intFromPtr(inst);
            const call_info = types.FFICallInfo.init(
                inst_addr,
                callee_name,
                classification,
                0.88,
                .go,
            );

            try result.addCall(call_info);

            if (classification == .returns_owned) {
                result.refcount_increments += 1;
            } else if (classification == .consumes_arg) {
                result.refcount_decrements += 1;
            }
        }
    }

    result.refcount_balance = @as(i32, @intCast(result.refcount_increments)) -
        @as(i32, @intCast(result.refcount_decrements));

    if (result.refcount_balance > 0) {
        result.has_potential_leak = true;
        result.leak_severity = if (result.refcount_balance > 2) .high else .medium;
    }

    // ═══════════════════════════════════════════════════════════
    // Memory Safety: malloc/free pairing detection
    // ═══════════════════════════════════════════════════════════
    // Track allocation/deallocation pairing for cgo FFI calls.
    // This implements single-function scope analysis as specified in
    // docs/v2/ffi_lang_support_plan.md Phase 1.
    var unpaired_allocs = std.ArrayList(types.FFICallInfo){};
    defer unpaired_allocs.deinit(allocator);

    for (result.ffi_calls.items) |call| {
        const callee_name = call.callee_name;

        if (isCgoAllocFunction(callee_name)) {
            try unpaired_allocs.append(allocator, call);
        }

        if (isCgoFreeFunction(callee_name)) {
            if (unpaired_allocs.items.len > 0) {
                _ = unpaired_allocs.pop();
            }
        }
    }

    // Report memory leaks for unpaired allocations
    for (unpaired_allocs.items) |alloc_call| {
        const func_name_ptr = c.LLVMGetValueName(llvm_func);
        const func_name_slice = if (func_name_ptr) |ptr|
            std.mem.span(ptr)
        else
            "unknown";

        const msg = try std.fmt.allocPrint(
            allocator,
            "[Go cgo] Memory leak: {s}() at instruction 0x{x} has no matching free in function '{s}'",
            .{ alloc_call.callee_name, alloc_call.inst_addr, func_name_slice },
        );

        const issue = types.AdapterIssue{
            .issue_type = .memory_leak,
            .message = msg,
            .location = types.IssueLocation.initWithAddr(func_name_slice, alloc_call.inst_addr),
            .severity = if (unpaired_allocs.items.len > 2) .high else .medium,
            .confidence = 0.75,
            .evidence = "cgo alloc/free pairing analysis",
        };

        try result.addIssue(issue);

        const log = std.log.scoped(.go_adapter);
        log.debug("DETECTED LEAK: {s} at 0x{x} in '{s}' (confidence={d:.2})", .{
            alloc_call.callee_name,
            alloc_call.inst_addr,
            func_name_slice,
            issue.confidence,
        });
    }

    result.is_analyzed = true;
    result.confidence = if (result.ffi_calls.items.len > 0) 0.88 else 0.15;

    return result;
}

/// Detect if a function name is a cgo-generated wrapper.
///
/// The cgo tool generates wrapper functions with the _Cgo_ prefix
/// to bridge Go and C calling conventions. These are the primary
/// FFI boundary indicators in compiled Go code.
pub fn isCGoWrapper(func_name: []const u8) bool {
    if (std.mem.startsWith(u8, func_name, CGO_WRAPPER_PREFIX)) return true;
    for (CGO_PATTERNS) |pattern| {
        if (std.mem.indexOf(u8, func_name, pattern) != null) return true;
    }
    return false;
}

/// Detect if a function is a Go runtime internal function.
///
/// Checks against the comprehensive RUNTIME_FUNCTIONS table plus
/// the broad "runtime." prefix catch-all for any runtime function
/// not explicitly listed.
pub fn isRuntimeFunction(func_name: []const u8) bool {
    // Check explicit table first
    for (RUNTIME_FUNCTIONS) |f| {
        if (std.mem.indexOf(u8, func_name, f) != null) return true;
    }

    // Broad prefix check for runtime package functions
    if (std.mem.startsWith(u8, func_name, "runtime.")) return true;

    return false;
}

/// Check if a function looks like a deferred cleanup call.
///
/// In Go, `defer C.free(ptr)` is the standard pattern for ensuring
/// C-allocated memory is released. These functions typically appear
/// in defer blocks and are called at function exit.
pub fn isLikelyDeferredCleanup(func_name: []const u8) bool {
    // C.* prefixed functions in defer context
    if (std.mem.startsWith(u8, func_name, "C.")) return true;
    // Common cleanup names
    if (std.mem.eql(u8, func_name, "close")) return true;
    if (std.mem.eql(u8, func_name, "destroy")) return true;
    return false;
}

/// Detect cross-language free pattern: Go allocator + C deallocator.
///
/// This is a common source of memory safety bugs in Go cgo code:
///   - runtime.mallocgc (Go GC heap) + free (C) → undefined behavior
///   - _cgo_allocate (Go) + free (C) → cross-language free
///   - C.CString (Go-allocated C memory) correctly freed by C.free ✓
pub fn isCrossLanguageFreePattern(go_alloc: []const u8, c_free: []const u8) bool {
    const go_allocators = [_][]const u8{
        "runtime.mallocgc",
        "runtime.newobject",
        "_cgo_allocate",
        "_Cfunc_GoMalloc",
        "runtime.alloc", // TinyGo
    };

    const c_deallocators = [_][]const u8{
        "free",
        "C.free",
        "_cgo_free",
        "_Cgo_free",
        "_Cfunc_GoFree",
    };

    var is_go_alloc = false;
    for (go_allocators) |alloc| {
        if (std.mem.indexOf(u8, go_alloc, alloc) != null) {
            is_go_alloc = true;
            break;
        }
    }

    var is_c_free = false;
    for (c_deallocators) |dealloc| {
        if (std.mem.indexOf(u8, c_free, dealloc) != null) {
            is_c_free = true;
            break;
        }
    }

    return is_go_alloc and is_c_free;
}

/// Detect potential memory leak pattern: C allocation without matching free.
///
/// Common in Go cgo when:
///   - C.CString / C.CBytes allocated but result discarded or leaked
///   - C.malloc called but C.free never called on the result
///   - Return value from owning function escapes without cleanup
pub fn isPotentialLeakPattern(alloc_call: []const u8, has_matching_free: bool) bool {
    const owning_calls = [_][]const u8{
        "C.CString",
        "C.CBytes",
        "C.malloc",
        "C.calloc",
        "C.strdup",
        "_Cgo_malloc",
    };

    var is_owning = false;
    for (owning_calls) |call| {
        if (std.mem.indexOf(u8, alloc_call, call) != null) {
            is_owning = true;
            break;
        }
    }

    return is_owning and !has_matching_free;
}

// ═══════════════════════════════════════════════════════════════
// Memory Safety Detection Helpers
// ═══════════════════════════════════════════════════════════════

/// Re-export AdapterIssueType from types.zig for convenience.
pub const AdapterIssueType = types.AdapterIssueType;

/// Check if callee is a known cgo allocation function.
///
/// These functions allocate C heap memory that must be explicitly freed:
///   - C.malloc / C.calloc / C.strdup: Standard C allocators
///   - C.CString / C.CBytes: Go→C conversion functions (call malloc internally)
///   - _cgo_allocate / _Cfunc_GoMalloc: cgo-generated wrappers
pub fn isCgoAllocFunction(callee_name: []const u8) bool {
    const CGO_ALLOC_FUNCTIONS = [_][]const u8{
        "C.malloc",
        "C.calloc",
        "C.strdup",
        "C.CString",
        "C.CBytes",
        "_cgo_allocate",
        "_Cgo_malloc",
        "_Cfunc_GoMalloc",
    };

    for (CGO_ALLOC_FUNCTIONS) |pattern| {
        if (std.mem.indexOf(u8, callee_name, pattern) != null) {
            return true;
        }
    }
    return false;
}

/// Check if callee is a known cgo deallocation function.
///
/// These functions release C heap memory:
///   - C.free: Standard C deallocator
///   - _cgo_free / _Cgo_free / _Cfunc_GoFree: cgo-generated wrappers
pub fn isCgoFreeFunction(callee_name: []const u8) bool {
    const CGO_FREE_FUNCTIONS = [_][]const u8{
        "C.free",
        "_cgo_free",
        "_Cgo_free",
        "_Cfunc_GoFree",
    };

    for (CGO_FREE_FUNCTIONS) |pattern| {
        if (std.mem.indexOf(u8, callee_name, pattern) != null) {
            return true;
        }
    }
    return false;
}

// ═══════════════════════════════════════════════════════════════
// Tests
// ═══════════════════════════════════════════════════════════════

test "GoAdapter - detects cgo wrappers" {
    try testing.expect(isCGoWrapper("_Cgo_malloc"));
    try testing.expect(isCGoWrapper("_Cgo_free"));
    try testing.expect(isCGoWrapper("_Cgo_ptr"));
    try testing.expect(isCGoWrapper("_cgo_123abc"));
    try testing.expect(isCGoWrapper("_Cfunc_foo"));

    // Not cgo wrappers
    try testing.expect(!isCGoWrapper("malloc"));
    try testing.expect(!isCGoWrapper("runtime.mallocgc"));
    try testing.expect(!isCGoWrapper("main.foo"));
}

test "GoAdapter - detects runtime functions" {
    try testing.expect(isRuntimeFunction("runtime.mallocgc"));
    try testing.expect(isRuntimeFunction("runtime.morestack"));
    try testing.expect(isRuntimeFunction("runtime.gopanic"));
    try testing.expect(isRuntimeFunction("runtime.deferreturn"));
    try testing.expect(isRuntimeFunction("runtime.gcStart"));

    // Not runtime functions
    try testing.expect(!isRuntimeFunction("main.foo"));
    try testing.expect(!isRuntimeFunction("malloc"));
    try testing.expect(!isRuntimeFunction("C.free"));
}

test "GoAdapter - classifies C allocator calls" {
    // C allocators return owned
    try testing.expectEqual(FFISemantics.returns_owned, instance.classifyCall("C.malloc"));
    try testing.expectEqual(FFISemantics.returns_owned, instance.classifyCall("C.calloc"));
    try testing.expectEqual(FFISemantics.returns_owned, instance.classifyCall("C.realloc"));

    // C.free consumes argument
    try testing.expectEqual(FFISemantics.consumes_arg, instance.classifyCall("C.free"));

    // C.strdup also returns owned (allocates memory via malloc)
    try testing.expectEqual(FFISemantics.returns_owned, instance.classifyCall("C.strdup"));
    try testing.expectEqual(FFISemantics.unknown, instance.classifyCall("C.getenv"));
}

test "GoAdapter - classifies cgo wrapper calls" {
    try testing.expectEqual(FFISemantics.returns_owned, instance.classifyCall("_Cgo_malloc"));
    try testing.expectEqual(FFISemantics.consumes_arg, instance.classifyCall("_Cgo_free"));
    try testing.expectEqual(FFISemantics.unknown, instance.classifyCall("_Cgo_ptr"));
}

test "GoAdapter - suppresses runtime functions" {
    try testing.expect(instance.shouldSuppress("runtime.mallocgc"));
    try testing.expect(instance.shouldSuppress("runtime.gopanic"));
    try testing.expect(instance.shouldSuppress("runtime.gcStart"));
    try testing.expect(instance.shouldSuppress("internal/abi.init"));

    // User code should NOT be suppressed
    try testing.expect(!instance.shouldSuppress("main.foo"));
    try testing.expect(!instance.shouldSuppress("C.malloc"));
    try testing.expect(!instance.shouldSuppress("malloc"));
}

test "GoAdapter - deferred cleanup detection" {
    try testing.expect(isLikelyDeferredCleanup("C.free"));
    try testing.expect(isLikelyDeferredCleanup("C.destroy"));
    try testing.expect(isLikelyDeferredCleanup("close"));

    // Not typical deferred cleanup
    try testing.expect(!isLikelyDeferredCleanup("malloc"));
    try testing.expect(!isLikelyDeferredCleanup("runtime.mallocgc"));
}

test "GoAdapter - instance metadata" {
    try testing.expectEqualStrings("go", instance.name);
    try testing.expectEqual(Language.go, instance.language);
    try testing.expectEqual(types.MemoryModel.hybrid, instance.memory_model);
}

test "GoAdapter - pattern lists" {
    const owning = instance.getOwningPatterns();
    const borrowing = instance.getBorrowingPatterns();

    try testing.expect(owning.len > 0);
    try testing.expect(borrowing.len == 0);

    // Verify C.malloc is in owning patterns
    var found_malloc: bool = false;
    for (owning) |p| {
        if (std.mem.eql(u8, p, "C.malloc")) found_malloc = true;
    }
    try testing.expect(found_malloc);
}

test "GoAdapter - classifies cgo conversion functions" {
    // Go → C conversions (allocate C memory)
    try testing.expectEqual(FFISemantics.returns_owned, instance.classifyCall("C.CString"));
    try testing.expectEqual(FFISemantics.returns_owned, instance.classifyCall("C.CBytes"));

    // C → Go conversions (borrow or copy)
    try testing.expectEqual(FFISemantics.returns_borrowed, instance.classifyCall("C.GoString"));
    try testing.expectEqual(FFISemantics.returns_borrowed, instance.classifyCall("C.GoStringN"));
    try testing.expectEqual(FFISemantics.returns_borrowed, instance.classifyCall("C.GoBytes"));
}

test "GoAdapter - cross-language free detection" {
    // Dangerous: Go allocator + C deallocator
    try testing.expect(isCrossLanguageFreePattern("runtime.mallocgc", "free"));
    try testing.expect(isCrossLanguageFreePattern("_cgo_allocate", "C.free"));
    try testing.expect(isCrossLanguageFreePattern("runtime.alloc", "_cgo_free")); // TinyGo

    // Safe: C.CString (allocates C memory) + C.free
    try testing.expect(!isCrossLanguageFreePattern("C.CString", "C.free"));

    // Safe: C allocator + C deallocator
    try testing.expect(!isCrossLanguageFreePattern("C.malloc", "C.free"));
}

test "GoAdapter - potential leak detection" {
    // Leak: allocation without free
    try testing.expect(isPotentialLeakPattern("C.CString", false));
    try testing.expect(isPotentialLeakPattern("C.CBytes", false));
    try testing.expect(isPotentialLeakPattern("C.malloc", false));

    // No leak: allocation with matching free
    try testing.expect(!isPotentialLeakPattern("C.CString", true));
    try testing.expect(!isPotentialLeakPattern("C.malloc", true));

    // Not an owning call
    try testing.expect(!isPotentialLeakPattern("C.GoString", false));
}

test "GoAdapter - suppresses compiler-generated symbols" {
    // Compiler-generated patterns should be suppressed
    try testing.expect(instance.shouldSuppress("go:itab.*os.File,io.Reader"));
    try testing.expect(instance.shouldSuppress("type:.hash.int"));
    try testing.expect(instance.shouldSuppress("type:.eqfunc.int"));
    try testing.expect(instance.shouldSuppress("main.inittask"));
    try testing.expect(instance.shouldSuppress("__cgo_puts"));
    try testing.expect(instance.shouldSuppress("gc.stackobject"));
    try testing.expect(instance.shouldSuppress("stackalloc"));
    try testing.expect(instance.shouldSuppress("reflect.typestr"));

    // User code should NOT be suppressed
    try testing.expect(!instance.shouldSuppress("main.foo"));
    try testing.expect(!instance.shouldSuppress("myFunction"));
}

test "GoAdapter - TinyGo runtime suppression" {
    // TinyGo-specific runtime functions
    try testing.expect(instance.shouldSuppress("runtime.alloc"));
    try testing.expect(instance.shouldSuppress("runtime.free"));
    try testing.expect(instance.shouldSuppress("runtime._panic"));
    try testing.expect(instance.shouldSuppress("runtime.trackPointer"));
    try testing.expect(instance.shouldSuppress("internal/task.start"));
}

// ═══════════════════════════════════════════════════════════════
// Phase 1: Memory Safety Detection Tests
// ═══════════════════════════════════════════════════════════════

test "GoAdapter - isCgoAllocFunction detects allocators" {
    // Standard C allocators
    try testing.expect(isCgoAllocFunction("C.malloc"));
    try testing.expect(isCgoAllocFunction("C.calloc"));
    try testing.expect(isCgoAllocFunction("C.strdup"));

    // Go→C conversion functions (allocate C memory)
    try testing.expect(isCgoAllocFunction("C.CString"));
    try testing.expect(isCgoAllocFunction("C.CBytes"));

    // cgo-generated wrappers
    try testing.expect(isCgoAllocFunction("_cgo_allocate"));
    try testing.expect(isCgoAllocFunction("_Cgo_malloc"));
    try testing.expect(isCgoAllocFunction("_Cfunc_GoMalloc"));

    // NOT allocators
    try testing.expect(!isCgoAllocFunction("C.free"));
    try testing.expect(!isCgoAllocFunction("C.getenv"));
    try testing.expect(!isCgoAllocFunction("runtime.mallocgc"));
    try testing.expect(!isCgoAllocFunction("main.foo"));
}

test "GoAdapter - isCgoFreeFunction detects deallocators" {
    // Standard C deallocator
    try testing.expect(isCgoFreeFunction("C.free"));

    // cgo-generated wrappers
    try testing.expect(isCgoFreeFunction("_cgo_free"));
    try testing.expect(isCgoFreeFunction("_Cgo_free"));
    try testing.expect(isCgoFreeFunction("_Cfunc_GoFree"));

    // NOT deallocators
    try testing.expect(!isCgoFreeFunction("C.malloc"));
    try testing.expect(!isCgoFreeFunction("C.CString"));
    try testing.expect(!isCgoFreeFunction("runtime.free"));
    try testing.expect(!isCgoFreeFunction("main.foo"));
}

test "GoAdapter - happy path: paired malloc/free produces no issues" {
    // Simulate a function with paired allocations
    var analysis = try types.AdapterAnalysis.init(testing.allocator, .go);
    defer analysis.deinit();

    // Add paired calls: malloc + free
    try analysis.addCall(types.FFICallInfo.init(0x1000, "C.malloc", .returns_owned, 0.88, .go));
    try analysis.addCall(types.FFICallInfo.init(0x1010, "C.free", .consumes_arg, 0.88, .go));

    // Run pairing detection (simplified version for testing)
    var unpaired_allocs = std.ArrayList(types.FFICallInfo){};
    defer {
        unpaired_allocs.deinit(testing.allocator);
    }

    for (analysis.ffi_calls.items) |call| {
        if (isCgoAllocFunction(call.callee_name)) {
            try unpaired_allocs.append(testing.allocator, call);
        }
        if (isCgoFreeFunction(call.callee_name)) {
            if (unpaired_allocs.items.len > 0) {
                _ = unpaired_allocs.pop();
            }
        }
    }

    // Should have no unpaired allocs (balanced)
    try testing.expectEqual(@as(usize, 0), unpaired_allocs.items.len);
}

test "GoAdapter - leak detection: unpaired malloc reports leak" {
    // Simulate a function with unpaired allocation
    var analysis = try types.AdapterAnalysis.init(testing.allocator, .go);
    defer analysis.deinit();

    // Add only malloc, no free
    try analysis.addCall(types.FFICallInfo.init(0x1000, "C.malloc", .returns_owned, 0.88, .go));
    try analysis.addCall(types.FFICallInfo.init(0x1020, "C.CString", .returns_owned, 0.88, .go));

    // Run pairing detection
    var unpaired_allocs = std.ArrayList(types.FFICallInfo){};
    defer {
        unpaired_allocs.deinit(testing.allocator);
    }

    for (analysis.ffi_calls.items) |call| {
        if (isCgoAllocFunction(call.callee_name)) {
            try unpaired_allocs.append(testing.allocator, call);
        }
        if (isCgoFreeFunction(call.callee_name)) {
            if (unpaired_allocs.items.len > 0) {
                _ = unpaired_allocs.pop();
            }
        }
    }

    // Should have 2 unpaired allocs (leak detected)
    try testing.expectEqual(@as(usize, 2), unpaired_allocs.items.len);

    // Verify the specific functions that leaked
    try testing.expectEqualStrings("C.malloc", unpaired_allocs.items[0].callee_name);
    try testing.expectEqualStrings("C.CString", unpaired_allocs.items[1].callee_name);
}

test "GoAdapter - multiple allocs with partial free" {
    // Simulate 3 allocs but only 2 frees → 1 leak
    var analysis = try types.AdapterAnalysis.init(testing.allocator, .go);
    defer analysis.deinit();

    // Alloc sequence: malloc, calloc, CString
    try analysis.addCall(types.FFICallInfo.init(0x1000, "C.malloc", .returns_owned, 0.88, .go));
    try analysis.addCall(types.FFICallInfo.init(0x1010, "C.calloc", .returns_owned, 0.88, .go));
    try analysis.addCall(types.FFICallInfo.init(0x1020, "C.CString", .returns_owned, 0.88, .go));

    // Free sequence: only 2 frees
    try analysis.addCall(types.FFICallInfo.init(0x1030, "C.free", .consumes_arg, 0.88, .go));
    try analysis.addCall(types.FFICallInfo.init(0x1040, "C.free", .consumes_arg, 0.88, .go));

    // Run pairing detection
    var unpaired_allocs = std.ArrayList(types.FFICallInfo){};
    defer {
        unpaired_allocs.deinit(testing.allocator);
    }

    for (analysis.ffi_calls.items) |call| {
        if (isCgoAllocFunction(call.callee_name)) {
            try unpaired_allocs.append(testing.allocator, call);
        }
        if (isCgoFreeFunction(call.callee_name)) {
            if (unpaired_allocs.items.len > 0) {
                _ = unpaired_allocs.pop();
            }
        }
    }

    // Should have exactly 1 unpaired alloc (the first malloc - LIFO order)
    try testing.expectEqual(@as(usize, 1), unpaired_allocs.items.len);
    try testing.expectEqualStrings("C.malloc", unpaired_allocs.items[0].callee_name);
}

test "GoAdapter - edge cases: empty and no-cgo functions" {
    // Test 1: Empty function (no calls at all)
    {
        var analysis = try types.AdapterAnalysis.init(testing.allocator, .go);
        defer analysis.deinit();

        try testing.expectEqual(@as(usize, 0), analysis.ffi_calls.items.len);
        try testing.expectEqual(@as(usize, 0), analysis.issues.items.len);
        try testing.expect(!analysis.has_potential_leak);
    }

    // Test 2: Function with non-cgo calls only
    {
        var analysis = try types.AdapterAnalysis.init(testing.allocator, .go);
        defer analysis.deinit();

        try analysis.addCall(types.FFICallInfo.init(0x1000, "runtime.mallocgc", .unknown, 0.5, .go));
        try analysis.addCall(types.FFICallInfo.init(0x1010, "main.helper", .unknown, 0.5, .go));

        // No cgo alloc/free calls should be detected
        var has_cgo_alloc = false;
        var has_cgo_free = false;
        for (analysis.ffi_calls.items) |call| {
            if (isCgoAllocFunction(call.callee_name)) has_cgo_alloc = true;
            if (isCgoFreeFunction(call.callee_name)) has_cgo_free = true;
        }

        try testing.expect(!has_cgo_alloc);
        try testing.expect(!has_cgo_free);
    }
}

test "GoAdapter - boundary: _Cgo_* variant recognition" {
    // Test all cgo wrapper variants are recognized as allocators/free
    const cgo_alloc_variants = [_][]const u8{
        "_Cgo_malloc",
        "_cgo_allocate",
        "_Cfunc_GoMalloc",
    };

    const cgo_free_variants = [_][]const u8{
        "_Cgo_free",
        "_cgo_free",
        "_Cfunc_GoFree",
    };

    for (cgo_alloc_variants) |variant| {
        try testing.expect(isCgoAllocFunction(variant));
    }

    for (cgo_free_variants) |variant| {
        try testing.expect(isCgoFreeFunction(variant));
    }

    // Mixed test: _Cgo_malloc + _Cgo_free should pair correctly
    var unpaired_allocs = std.ArrayList(types.FFICallInfo){};
    defer {
        unpaired_allocs.deinit(testing.allocator);
    }

    const alloc_call = types.FFICallInfo.init(0x1000, "_Cgo_malloc", .returns_owned, 0.88, .go);
    const free_call = types.FFICallInfo.init(0x1010, "_Cgo_free", .consumes_arg, 0.88, .go);

    try unpaired_allocs.append(testing.allocator, alloc_call);
    try testing.expectEqual(@as(usize, 1), unpaired_allocs.items.len);

    // Simulate free pairing
    if (isCgoFreeFunction(free_call.callee_name) and unpaired_allocs.items.len > 0) {
        _ = unpaired_allocs.pop();
    }

    try testing.expectEqual(@as(usize, 0), unpaired_allocs.items.len);
}

test "GoAdapter - AdapterIssueType toIssueKind mapping" {
    // Verify mapping from adapter-specific issue types to canonical IssueKind
    const IssueKind = @import("../common/types.zig").IssueKind;

    try testing.expectEqual(IssueKind.memory_leak, AdapterIssueType.memory_leak.toIssueKind());
    try testing.expectEqual(IssueKind.use_after_free, AdapterIssueType.use_after_free.toIssueKind());
    try testing.expectEqual(IssueKind.ffi_unsafe_call, AdapterIssueType.gil_violation.toIssueKind());
    try testing.expectEqual(IssueKind.use_after_free, AdapterIssueType.borrowed_ref_error.toIssueKind());
    try testing.expectEqual(IssueKind.memory_leak, AdapterIssueType.buffer_leak.toIssueKind());
    try testing.expectEqual(IssueKind.unchecked_return, AdapterIssueType.null_return_not_checked.toIssueKind());
    try testing.expectEqual(IssueKind.use_after_free, AdapterIssueType.stale_interpreter_ptr.toIssueKind());
}

const testing = std.testing;
